import { FACTION_BY_ID } from './factions';
import { CardDefinitionSchema } from './schemas';
import type { CardDefinition, CardSfx, FactionId, ManaCost } from './types';

type CardSeed = Omit<
  CardDefinition,
  'color' | 'art' | 'set' | 'artist' | 'unlocked' | 'sfx'
> & { readonly sfx?: CardSfx; readonly set?: string };

/** Nombre del conjunto de la segunda oleada, para no repetirlo 24 veces. */
const SECOND_WAVE_SET = 'NEX-02 · Fractura';

const factionCost = (faction: FactionId, colored: number, generic = 0): ManaCost => ({
  generic,
  colored: colored === 0 ? {} : { [faction]: colored },
});

const ARTIST_CREDITS: Readonly<Record<string, string>> = Object.freeze({
  'fuente-furia': 'L. Valcazar, M. Iriarte & Taller de Luz Volcanica',
  'sabueso-brasa': 'V. Sanz, I. Rauk & Taller de Bestiario Igneo',
  'berserker-ignivoro': 'A. Montiel, C. Nervo & Taller de Oleo Heroico',
  'dragon-caldera': 'S. Aranda, D. Korr & Taller de Mural Epico',
  'lluvia-ceniza': 'N. Beltran, E. Ros & Taller de Atmosfera Negra',
  'forja-carmesi': 'P. Duarte, L. Maceira & Taller de Metal Ritual',
  'lancera-magma': 'R. Astar, M. Quiral & Taller de Figura Dinamica',
  'fenix-pavesa': 'C. Echevarri, A. Soler & Taller de Gouache Luminoso',
  'ariete-volcanico': 'B. Iriondo, T. Mallo & Taller de Perspectiva Baja',
  'pacto-ascuas': 'F. Lera, O. Vey & Taller de Ritual Intimo',
  'altar-combustion': 'H. Nadir, S. Coto & Taller Simbolista',
  'temblor-rojo': 'D. Salvat, J. Roca & Taller de Paisaje Cataclismico',
  'erupcion-volcanica': 'N. Beltran, E. Ros & Taller de Atmosfera Negra Expandida',
  'gigante-magma': 'L. Valcazar, J. Fuentes & Taller de Titan Igneo',
  'draco-magma': 'S. Aranda, D. Korr & Taller de Dragón Abismal',
  'infiltrado-volcanico': 'V. Sanz, T. Noir & Taller de Sombra Ardiente',
  'elemental-tormenta': 'N. Beltran, E. Ros & Taller de Clima Elemental',
  'fuente-arcana': 'M. Olarte, L. Vesper & Taller de Acuarela Luminica',
  'centinela-cristal': 'E. Rivas, N. Calve & Taller de Prisma Mineral',
  'tejedora-escarcha': 'I. Llorens, A. Vela & Taller de Figura Elegante',
  'prision-glacial': 'Q. Soria, L. Mael & Taller de Arquitectura Fria',
  'cometa-arcano': 'T. Nerea, B. Voss & Taller Astronomico',
  'torre-horizonte': 'G. Estel, M. Bruma & Taller de Arquitectura Romantica',
  'duelista-prisma': 'A. Faber, C. Lince & Taller de Esgrima Prismatica',
  'golem-azur': 'R. Navas, E. Aro & Taller de Criatura Mineral',
  'niebla-espejada': 'V. Merin, S. Albor & Taller de Nocturno Surreal',
  'eco-cronomante': 'J. Auren, P. Sibil & Taller Simbolista Arcano',
  'archivo-viviente': 'M. Doria, H. Clave & Taller de Biblioteca Imposible',
  'convergencia-astral': 'K. Morat, I. Serna & Taller de Geometria Cosmica',
  'congelacion-rapida': 'Q. Soria, L. Mael & Taller de Hielo Explosivo',
  'dragon-escarcha': 'E. Rivas, N. Calve & Taller de Dragón Glacial',
  'guardian-escarchado': 'R. Navas, E. Aro & Taller de Centinela Perenne',
  'destello-runico': 'T. Nerea, B. Voss & Taller de Magia Refulgente',
  'mago-celestial': 'M. Olarte, L. Vesper & Taller de Mago Estelar',
});

const defineCard = (seed: CardSeed): CardDefinition => {
  const definition: CardDefinition = {
    ...seed,
    color: FACTION_BY_ID[seed.faction].color,
    art: {
      webp: `/assets/cards/art/${seed.id}.webp`,
      fallback: `/assets/cards/art/${seed.id}.svg`,
      alt: `Ilustración de ${seed.name}`,
    },
    set: seed.set ?? 'NEX-01 · Despertar',
    artist: ARTIST_CREDITS[seed.id] ?? 'Atelier del Nexo',
    unlocked: true,
    sfx: seed.sfx ?? { play: `${seed.faction}-play`, impact: `${seed.faction}-impact` },
  };
  return CardDefinitionSchema.parse(definition) as CardDefinition;
};

const furyCards: readonly CardDefinition[] = [
  defineCard({
    id: 'fuente-furia', name: 'Fuente de Furia', faction: 'fury', type: 'mana', subtype: 'Fuente',
    rarity: 'common', cost: factionCost('fury', 0),
    rules: 'Agota esta fuente: genera 1 de Esencia Carmesí.',
    flavor: 'Bajo la montaña, el corazón del mundo todavía arde.',
    keywords: [], collectorNumber: 1, aiTags: ['resource'], unique: false, effects: [],
    vfx: { persistentEffect: 'fury-source-embers' }, sfx: { play: 'resource-fury' },
  }),
  defineCard({
    id: 'sabueso-brasa', name: 'Sabueso de Brasa', faction: 'fury', type: 'unit', subtype: 'Bestia',
    rarity: 'common', cost: factionCost('fury', 1), attack: 2, health: 1, range: 1, movement: 2,
    rules: 'Impulso: puede moverse el turno en que entra en juego.',
    flavor: 'No persigue el olor de la sangre, sino el miedo que la precede.',
    keywords: ['impulse'], collectorNumber: 2, aiTags: ['aggressive', 'fast'], unique: false, effects: [],
    vfx: { summonEffect: 'ember-pounce', attackEffect: 'ember-trail', deathEffect: 'ash-burst' },
  }),
  defineCard({
    id: 'berserker-ignivoro', name: 'Berserker Ignívoro', faction: 'fury', type: 'unit', subtype: 'Guerrero',
    rarity: 'uncommon', cost: factionCost('fury', 2, 1), attack: 3, health: 3, range: 1, movement: 2,
    rules: 'Cuando ataque por primera vez cada turno, obtiene +1 Ataque durante ese combate.',
    flavor: 'Cada cicatriz es una puerta por la que vuelve a entrar el fuego.',
    keywords: [], collectorNumber: 3, aiTags: ['aggressive', 'combat'], unique: false,
    effects: [{ kind: 'buff-self-on-attack', attack: 1 }],
    vfx: { summonEffect: 'fury-cracks', attackEffect: 'rage-flare', impactEffect: 'heavy-impact' },
  }),
  defineCard({
    id: 'dragon-caldera', name: 'Dragón de la Caldera', faction: 'fury', type: 'unit', subtype: 'Dragón',
    rarity: 'mythic', cost: factionCost('fury', 2, 5), attack: 7, health: 6, range: 1, movement: 2,
    rules: 'Al entrar en juego, inflige 2 de daño a todas las demás cartas de las casillas adyacentes.',
    flavor: 'La Caldera no entró en erupción. Simplemente abrió los ojos.',
    keywords: [], collectorNumber: 4, aiTags: ['finisher', 'area-damage'], unique: true,
    effects: [{ kind: 'adjacent-damage', amount: 2, includeAllies: true }],
    vfx: { summonEffect: 'caldera-eruption', attackEffect: 'dragon-flame', deathEffect: 'volcanic-collapse' },
  }),
  defineCard({
    id: 'lluvia-ceniza', name: 'Lluvia de Ceniza', faction: 'fury', type: 'instant', subtype: 'Conjuro',
    rarity: 'uncommon', cost: factionCost('fury', 1, 2),
    rules: 'Inflige 2 de daño a una unidad. Su casilla queda abrasada hasta el final del siguiente turno.',
    flavor: 'Cuando el cielo se vuelve gris, hasta las sombras buscan refugio.',
    keywords: [], collectorNumber: 5, aiTags: ['removal', 'damage'], unique: false,
    effects: [{ kind: 'damage', amount: 2, target: 'enemy-piece' }, { kind: 'scorch', duration: 1 }],
    vfx: { impactEffect: 'ash-rain', persistentEffect: 'scorched-tile' }, sfx: { play: 'ash-rain', impact: 'fire-impact' },
  }),
  defineCard({
    id: 'forja-carmesi', name: 'Forja Carmesí', faction: 'fury', type: 'structure', subtype: 'Forja',
    rarity: 'rare', cost: factionCost('fury', 1, 2), resistance: 5,
    rules: 'La primera unidad de Furia que juegues cada turno obtiene +1 Ataque hasta el final del turno.',
    flavor: 'Aquí no se fabrican armas. Se despierta su hambre.',
    keywords: [], collectorNumber: 6, aiTags: ['structure', 'buff'], unique: false,
    effects: [{ kind: 'passive', id: 'first-fury-unit-attack', value: 1 }],
    vfx: { summonEffect: 'forge-rise', persistentEffect: 'forge-glow', deathEffect: 'forge-collapse' },
  }),
  defineCard({
    id: 'lancera-magma', name: 'Lancera de Magma', faction: 'fury', type: 'unit', subtype: 'Guerrera',
    rarity: 'common', cost: factionCost('fury', 1, 1), attack: 2, health: 2, range: 1, movement: 2,
    rules: 'Impulso. Puede avanzar hasta 2 casillas si ambas están libres.',
    flavor: 'La lava siempre encuentra una grieta; su lanza también.',
    keywords: ['impulse'], collectorNumber: 7, aiTags: ['fast', 'flanker'], unique: false, effects: [],
    vfx: { summonEffect: 'slag-sparks', attackEffect: 'cinder-dash' },
  }),
  defineCard({
    id: 'fenix-pavesa', name: 'Fénix de Pavesa', faction: 'fury', type: 'unit', subtype: 'Ave ígnea',
    rarity: 'uncommon', cost: factionCost('fury', 1, 2), attack: 2, health: 3, range: 2, movement: 2,
    rules: 'Al entrar en juego, inflige 1 de daño a una carta enemiga adyacente.',
    flavor: 'Cada una de sus plumas recuerda un incendio distinto.',
    keywords: ['flying'], collectorNumber: 8, aiTags: ['ranged', 'damage'], unique: false,
    effects: [{ kind: 'passive', id: 'entry-adjacent-enemy-damage', value: 1 }],
    vfx: { summonEffect: 'rift-open', attackEffect: 'fire-bolt', impactEffect: 'magma-pop' },
  }),
  defineCard({
    id: 'ariete-volcanico', name: 'Ariete Volcánico', faction: 'fury', type: 'unit', subtype: 'Constructo',
    rarity: 'rare', cost: factionCost('fury', 2, 2), attack: 4, health: 5, range: 1, movement: 1,
    rules: 'Perforar. Cuando daña una estructura, inflige 2 de daño adicional.',
    flavor: 'La puerta cede mucho antes que la piedra se canse.',
    keywords: ['pierce'], collectorNumber: 9, aiTags: ['siege', 'durable'], unique: false,
    effects: [{ kind: 'passive', id: 'structure-bonus-damage', value: 2 }],
    vfx: { summonEffect: 'basalt-drop', attackEffect: 'siege-charge', impactEffect: 'stone-shockwave' },
  }),
  defineCard({
    id: 'pacto-ascuas', name: 'Pacto de Ascuas', faction: 'fury', type: 'instant', subtype: 'Ritual',
    rarity: 'rare', cost: factionCost('fury', 1, 1),
    rules: 'Una unidad aliada obtiene +2 Ataque hasta el final del turno.',
    flavor: 'Un juramento pronunciado sobre carbón nunca se enfría.',
    keywords: [], collectorNumber: 10, aiTags: ['buff', 'combat'], unique: false,
    effects: [{ kind: 'passive', id: 'target-attack-until-end', value: 2 }],
    vfx: { impactEffect: 'ember-oath' },
  }),
  defineCard({
    id: 'altar-combustion', name: 'Altar de Combustión', faction: 'fury', type: 'structure', subtype: 'Altar',
    rarity: 'common', cost: factionCost('fury', 1, 1), resistance: 4,
    rules: 'Las unidades enemigas no pueden atravesar esta casilla.',
    flavor: 'La llama acepta todas las ofrendas y nunca concede absolución.',
    keywords: ['guard'], collectorNumber: 11, aiTags: ['structure', 'defense'], unique: false,
    effects: [{ kind: 'passive', id: 'blocking-structure' }],
    vfx: { summonEffect: 'magma-wall', persistentEffect: 'heat-haze' },
  }),
  defineCard({
    id: 'temblor-rojo', name: 'Temblor Rojo', faction: 'fury', type: 'instant', subtype: 'Cataclismo',
    rarity: 'rare', cost: factionCost('fury', 2, 2),
    rules: 'Inflige 3 de daño a una unidad. Después, la réplica inflige 1 de daño a la unidad enemiga más debilitada restante.',
    flavor: 'La tierra aprende a rugir antes de abrirse.',
    keywords: [], collectorNumber: 12, aiTags: ['removal', 'damage'], unique: false,
    effects: [{ kind: 'damage', amount: 3, target: 'enemy-piece' }, { kind: 'splash-weakest-enemy', amount: 1 }],
    vfx: { impactEffect: 'chain-eruption', persistentEffect: 'magma-chain' },
  }),
  defineCard({
    id: 'erupcion-volcanica', name: 'Erupción Volcánica', faction: 'fury', type: 'instant', subtype: 'Catástrofe',
    rarity: 'uncommon', cost: factionCost('fury', 1, 2),
    rules: 'Inflige 2 de daño a cada unidad enemiga. Las casillas afectadas permanecen abrasadas.',
    flavor: 'El cielo se parte cuando la tierra elige hablar.',
    keywords: [], collectorNumber: 25, aiTags: ['removal', 'area-damage'], unique: false,
    effects: [{ kind: 'damage-all-enemies', amount: 2, scorch: true }],
    vfx: { impactEffect: 'volcanic-burst', persistentEffect: 'lava-shockwave' },
  }),
  defineCard({
    id: 'gigante-magma', name: 'Gigante de Magma', faction: 'fury', type: 'unit', subtype: 'Gigante',
    rarity: 'rare', cost: factionCost('fury', 3, 2), attack: 5, health: 6, range: 1, movement: 1,
    rules: 'Perforar. Las casillas adyacentes permanecen abrasadas.',
    flavor: 'Cada paso deja un valle de fuego donde antes había tierra fértil.',
    keywords: ['pierce'], collectorNumber: 26, aiTags: ['durable', 'area-control'], unique: false,
    effects: [{ kind: 'passive', id: 'scorch-adjacents' }],
    vfx: { summonEffect: 'magma-rise', persistentEffect: 'heat-aura' },
  }),
  defineCard({
    id: 'draco-magma', name: 'Draco de Magma', faction: 'fury', type: 'unit', subtype: 'Dragón',
    rarity: 'mythic', cost: factionCost('fury', 2, 4), attack: 6, health: 5, range: 2, movement: 2,
    rules: 'Impulso. Cuando ataca, las casillas adyacentes al objetivo reciben daño de fuego.',
    flavor: 'Su aliento convierte arena en cristal, en un instante.',
    keywords: ['impulse'], collectorNumber: 27, aiTags: ['finisher', 'ranged'], unique: false,
    effects: [{ kind: 'adjacent-damage', amount: 1, includeAllies: false, trigger: 'attack' }],
    vfx: { summonEffect: 'dragon-awaken', attackEffect: 'magma-beam', deathEffect: 'dragon-collapse' },
  }),
  defineCard({
    id: 'infiltrado-volcanico', name: 'Infiltrado Volcánico', faction: 'fury', type: 'unit', subtype: 'Bandido',
    rarity: 'common', cost: factionCost('fury', 1), attack: 2, health: 2, range: 1, movement: 2,
    rules: 'Impulso: puede moverse el turno en que entra en juego. +1 Ataque contra unidades solitarias.',
    flavor: 'Aparece donde nadie lo espera y desaparece en el humo.',
    keywords: ['impulse'], collectorNumber: 28, aiTags: ['aggressive', 'assassin'], unique: false,
    effects: [{ kind: 'passive', id: 'bonus-damage-isolated-target', value: 1 }],
    vfx: { summonEffect: 'smoke-rise', attackEffect: 'cinder-strike' },
  }),
  defineCard({
    id: 'elemental-tormenta', name: 'Elemental de Tormenta', faction: 'fury', type: 'unit', subtype: 'Elemental',
    rarity: 'uncommon', cost: factionCost('fury', 1, 2), attack: 2, health: 4, range: 2, movement: 2,
    rules: 'Rango 2. Cuando ataca, inflige 1 de daño adicional a la unidad objetivo.',
    flavor: 'Nubes ardientes que gritan en lengua de trueno y ceniza.',
    keywords: [], collectorNumber: 34, aiTags: ['ranged', 'damage'], unique: false,
    effects: [{ kind: 'damage', amount: 1, target: 'enemy-piece' }],
    vfx: { summonEffect: 'storm-gather', attackEffect: 'lightning-strike', impactEffect: 'thunder-boom' },
  }),
];

const arcaneCards: readonly CardDefinition[] = [
  defineCard({
    id: 'fuente-arcana', name: 'Fuente Arcana', faction: 'arcane', type: 'mana', subtype: 'Fuente',
    rarity: 'common', cost: factionCost('arcane', 0),
    rules: 'Agota esta fuente: genera 1 de Esencia Celeste.',
    flavor: 'Cada cristal conserva una pregunta que el mundo aún no sabe responder.',
    keywords: [], collectorNumber: 13, aiTags: ['resource'], unique: false, effects: [],
    vfx: { persistentEffect: 'arcane-source-runes' }, sfx: { play: 'resource-arcane' },
  }),
  defineCard({
    id: 'centinela-cristal', name: 'Centinela de Cristal', faction: 'arcane', type: 'unit', subtype: 'Constructo',
    rarity: 'common', cost: factionCost('arcane', 1, 1), attack: 1, health: 3, range: 1, movement: 1,
    rules: 'Al entrar en juego, observa las dos primeras cartas de tu mazo y colócalas en el orden que quieras.',
    flavor: 'No piensa, no duerme y jamás olvida una orden.',
    keywords: [], collectorNumber: 14, aiTags: ['defense', 'scry'], unique: false,
    effects: [{ kind: 'scry', amount: 2 }],
    vfx: { summonEffect: 'crystal-assemble', attackEffect: 'crystal-swipe', deathEffect: 'crystal-shatter' },
  }),
  defineCard({
    id: 'tejedora-escarcha', name: 'Tejedora de Escarcha', faction: 'arcane', type: 'unit', subtype: 'Hechicera',
    rarity: 'uncommon', cost: factionCost('arcane', 2, 1), attack: 2, health: 3, range: 2, movement: 2,
    rules: 'Cuando dañe a una unidad, esa unidad no podrá moverse durante su próximo turno.',
    flavor: 'Con un gesto detiene el agua. Con una palabra, detiene ejércitos.',
    keywords: [], collectorNumber: 15, aiTags: ['ranged', 'control'], unique: false,
    effects: [{ kind: 'passive', id: 'freeze-on-damage', value: 1 }],
    vfx: { summonEffect: 'frost-weave', attackEffect: 'ice-thread', impactEffect: 'freeze-lock' },
  }),
  defineCard({
    id: 'prision-glacial', name: 'Prisión Glacial', faction: 'arcane', type: 'instant', subtype: 'Encantamiento',
    rarity: 'uncommon', cost: factionCost('arcane', 1, 1),
    rules: 'Congela una unidad hasta el comienzo de tu siguiente turno. No puede moverse ni atacar.',
    flavor: 'El hielo no encierra el cuerpo. Convence al tiempo de que deje de avanzar.',
    keywords: [], collectorNumber: 16, aiTags: ['freeze', 'control'], unique: false,
    effects: [{ kind: 'freeze', duration: 1 }],
    vfx: { impactEffect: 'glacial-prison', persistentEffect: 'frozen-runes' },
  }),
  defineCard({
    id: 'cometa-arcano', name: 'Cometa Arcano', faction: 'arcane', type: 'instant', subtype: 'Evocación',
    rarity: 'rare', cost: factionCost('arcane', 2, 3),
    rules: 'Inflige 4 de daño a una unidad o estructura. Si el objetivo estaba congelado, inflige 2 de daño adicional.',
    flavor: 'Los sabios estudian las estrellas. Los necios esperan a que caigan.',
    keywords: [], collectorNumber: 17, aiTags: ['removal', 'damage'], unique: false,
    effects: [{ kind: 'damage', amount: 4, target: 'any-piece' }, { kind: 'passive', id: 'frozen-bonus-damage', value: 2 }],
    vfx: { impactEffect: 'arcane-comet' }, sfx: { play: 'comet-cast', impact: 'comet-impact' },
  }),
  defineCard({
    id: 'torre-horizonte', name: 'Torre del Horizonte', faction: 'arcane', type: 'structure', subtype: 'Observatorio',
    rarity: 'rare', cost: factionCost('arcane', 1, 3), resistance: 5,
    rules: 'Una vez por turno, después de lanzar un hechizo, puedes robar una carta y descartar otra.',
    flavor: 'Desde lo alto puede verse el futuro, pero nunca el precio de alcanzarlo.',
    keywords: [], collectorNumber: 18, aiTags: ['structure', 'draw'], unique: false,
    effects: [{ kind: 'passive', id: 'loot-after-spell', value: 1 }],
    vfx: { summonEffect: 'tower-rise', persistentEffect: 'horizon-orbit', deathEffect: 'rune-collapse' },
  }),
  defineCard({
    id: 'duelista-prisma', name: 'Duelista del Prisma', faction: 'arcane', type: 'unit', subtype: 'Místico',
    rarity: 'common', cost: factionCost('arcane', 1), attack: 1, health: 2, range: 1, movement: 2,
    rules: 'Aturdir. Al entrar en juego, roba una carta y luego descarta una carta.',
    flavor: 'Su hoja elige un color distinto para cada adversario.',
    keywords: ['stun'], collectorNumber: 19, aiTags: ['draw', 'utility'], unique: false,
    effects: [{ kind: 'draw', amount: 1 }, { kind: 'discard', amount: 1 }],
    vfx: { summonEffect: 'seven-runes', attackEffect: 'rune-pulse' },
  }),
  defineCard({
    id: 'golem-azur', name: 'Gólem Azur', faction: 'arcane', type: 'unit', subtype: 'Constructo',
    rarity: 'uncommon', cost: factionCost('arcane', 1, 2), attack: 2, health: 5, range: 1, movement: 1,
    rules: 'La primera vez que reciba daño cada turno, reduce ese daño en 1.',
    flavor: 'Su núcleo contiene un mar que jamás conoció orillas.',
    keywords: ['guard'], collectorNumber: 20, aiTags: ['defense', 'durable'], unique: false,
    effects: [{ kind: 'passive', id: 'first-damage-reduction', value: 1 }],
    vfx: { summonEffect: 'azur-assemble', impactEffect: 'water-shield', deathEffect: 'azur-shatter' },
  }),
  defineCard({
    id: 'niebla-espejada', name: 'Niebla Espejada', faction: 'arcane', type: 'instant', subtype: 'Encantamiento',
    rarity: 'rare', cost: factionCost('arcane', 2, 1),
    rules: 'Observa las tres primeras cartas de tu mazo y colócalas en el orden que quieras. Después, roba una carta.',
    flavor: 'Cada reflejo oculta a quien lo está mirando.',
    keywords: [], collectorNumber: 21, aiTags: ['scry', 'draw'], unique: false,
    effects: [{ kind: 'scry', amount: 3 }, { kind: 'draw', amount: 1 }],
    vfx: { summonEffect: 'mirror-unfold', persistentEffect: 'probability-shimmer' },
  }),
  defineCard({
    id: 'eco-cronomante', name: 'Eco Cronomante', faction: 'arcane', type: 'instant', subtype: 'Cronomancia',
    rarity: 'common', cost: factionCost('arcane', 1, 1),
    rules: 'Roba 2 cartas y luego descarta una carta.',
    flavor: 'Su voz llega siempre un instante antes que sus labios.',
    keywords: [], collectorNumber: 22, aiTags: ['draw', 'selection'], unique: false,
    effects: [{ kind: 'draw', amount: 2 }, { kind: 'discard', amount: 1 }],
    vfx: { impactEffect: 'time-current' },
  }),
  defineCard({
    id: 'archivo-viviente', name: 'Archivo Viviente', faction: 'arcane', type: 'unit', subtype: 'Místico',
    rarity: 'mythic', cost: factionCost('arcane', 2, 4), attack: 4, health: 6, range: 2, movement: 1,
    rules: 'Al entrar en juego, roba 2 cartas. Tus hechizos cuestan 1 genérico menos, hasta un mínimo de 0.',
    flavor: 'Ha catalogado cada final salvo el suyo.',
    keywords: [], collectorNumber: 23, aiTags: ['finisher', 'draw'], unique: true,
    effects: [{ kind: 'draw', amount: 2 }, { kind: 'passive', id: 'spell-generic-discount', value: 1 }],
    vfx: { summonEffect: 'infinite-library', attackEffect: 'glyph-beam', deathEffect: 'pages-to-stars' },
  }),
  defineCard({
    id: 'convergencia-astral', name: 'Convergencia Astral', faction: 'arcane', type: 'instant', subtype: 'Portal',
    rarity: 'uncommon', cost: factionCost('arcane', 1, 2),
    rules: 'Una unidad aliada puede moverse de nuevo este turno, aunque acabe de entrar en juego.',
    flavor: 'Cuando las estrellas coinciden, la distancia pierde toda autoridad.',
    keywords: [], collectorNumber: 24, aiTags: ['movement', 'control'], unique: false,
    effects: [{ kind: 'refresh-move' }],
    vfx: { impactEffect: 'folded-threshold', persistentEffect: 'portal-ripple' },
  }),
  defineCard({
    id: 'congelacion-rapida', name: 'Congelación Rápida', faction: 'arcane', type: 'instant', subtype: 'Encantamiento',
    rarity: 'common', cost: factionCost('arcane', 1, 1),
    rules: 'Congela una unidad enemiga durante 1 turno. No puede moverse ni atacar.',
    flavor: 'El tiempo se quiebra bajo el hielo.',
    keywords: [], collectorNumber: 29, aiTags: ['freeze', 'control'], unique: false,
    effects: [{ kind: 'freeze', duration: 1 }],
    vfx: { impactEffect: 'instant-freeze', persistentEffect: 'ice-shards' },
  }),
  defineCard({
    id: 'dragon-escarcha', name: 'Dragón de Escarcha', faction: 'arcane', type: 'unit', subtype: 'Dragón',
    rarity: 'mythic', cost: factionCost('arcane', 2, 4), attack: 5, health: 7, range: 2, movement: 2,
    rules: 'Cuando ataca, congela el objetivo durante el siguiente turno. Las unidades congeladas no pueden atacar.',
    flavor: 'Su cola barre el horizonte dejando nieve donde antes ardía.',
    keywords: [], collectorNumber: 30, aiTags: ['finisher', 'control'], unique: false,
    effects: [{ kind: 'freeze', duration: 1 }],
    vfx: { summonEffect: 'frost-awaken', attackEffect: 'ice-beam', deathEffect: 'snowstorm' },
  }),
  defineCard({
    id: 'guardian-escarchado', name: 'Guardián Escarchado', faction: 'arcane', type: 'unit', subtype: 'Constructo',
    rarity: 'uncommon', cost: factionCost('arcane', 1, 2), attack: 1, health: 5, range: 1, movement: 1, resistance: 3,
    rules: 'Las unidades enemigas adyacentes no pueden atacar.',
    flavor: 'Ni se mueve ni cede. Simplemente espera a que todo se paralice.',
    keywords: ['guard'], collectorNumber: 31, aiTags: ['defense', 'freeze'], unique: false,
    effects: [{ kind: 'passive', id: 'pacify-adjacent-enemies' }],
    vfx: { summonEffect: 'ice-wall', persistentEffect: 'permafrost-aura' },
  }),
  defineCard({
    id: 'destello-runico', name: 'Destello Rúnico', faction: 'arcane', type: 'instant', subtype: 'Hechizo',
    rarity: 'uncommon', cost: factionCost('arcane', 1, 1),
    rules: 'Inflige 2 de daño a una unidad enemiga. Roba una carta.',
    flavor: 'Cada runa que desata revela un secreto del universo.',
    keywords: [], collectorNumber: 32, aiTags: ['damage', 'draw'], unique: false,
    effects: [{ kind: 'damage', amount: 2, target: 'enemy-piece' }, { kind: 'draw', amount: 1 }],
    vfx: { impactEffect: 'rune-flash', persistentEffect: 'knowledge-surge' },
  }),
  defineCard({
    id: 'mago-celestial', name: 'Mago Celestial', faction: 'arcane', type: 'unit', subtype: 'Mago',
    rarity: 'rare', cost: factionCost('arcane', 1, 3), attack: 3, health: 3, range: 3, movement: 1,
    rules: 'Rango 3. Gana +1 Ataque cuando ataca desde casillas no adyacentes.',
    flavor: 'Ve más allá de las nubes, donde habita el lenguaje de los dioses.',
    keywords: [], collectorNumber: 33, aiTags: ['ranged', 'spell-synergy'], unique: false,
    effects: [{ kind: 'passive', id: 'ranged-attack-bonus', value: 1 }],
    vfx: { summonEffect: 'celestial-descent', attackEffect: 'starlight-bolt', persistentEffect: 'cosmic-aura' },
  }),
];

const natureCards: readonly CardDefinition[] = [
  defineCard({
    id: 'fuente-naturaleza', name: 'Fuente Naturaleza', faction: 'nature', type: 'mana', subtype: 'Fuente',
    rarity: 'common', cost: factionCost('nature', 0),
    rules: 'Agota esta fuente: genera 1 de Esencia Verdadera.',
    flavor: 'La tierra respira en ciclos sin fin.',
    keywords: [], collectorNumber: 35, aiTags: ['resource'], unique: false, effects: [],
    vfx: { persistentEffect: 'nature-source-growth' }, sfx: { play: 'resource-nature' },
  }),
  defineCard({
    id: 'ciervo-sagrado', name: 'Ciervo Sagrado', faction: 'nature', type: 'unit', subtype: 'Bestia',
    rarity: 'common', cost: factionCost('nature', 1), attack: 2, health: 2, range: 1, movement: 1,
    rules: 'Al entrar en juego, roba una carta.',
    flavor: 'Sus astas atrapan la luz del bosque.',
    keywords: [], collectorNumber: 36, aiTags: ['draw', 'utility'], unique: false, effects: [{ kind: 'draw', amount: 1 }],
    vfx: { summonEffect: 'antler-glow', attackEffect: 'leaf-strike' },
  }),
  defineCard({
    id: 'lobo-salvaje', name: 'Lobo Salvaje', faction: 'nature', type: 'unit', subtype: 'Bestia',
    rarity: 'common', cost: factionCost('nature', 1), attack: 2, health: 2, range: 1, movement: 2,
    rules: 'Impulso: puede moverse el turno en que entra en juego.',
    flavor: 'Caza en manadas donde nadie osa entrar.',
    keywords: ['impulse'], collectorNumber: 37, aiTags: ['aggressive', 'fast'], unique: false, effects: [],
    vfx: { summonEffect: 'howl-echo', attackEffect: 'pounce-strike' },
  }),
  defineCard({
    id: 'oso-forestal', name: 'Oso Forestal', faction: 'nature', type: 'unit', subtype: 'Bestia',
    rarity: 'uncommon', cost: factionCost('nature', 2, 1), attack: 4, health: 4, range: 1, movement: 1, resistance: 2,
    rules: 'Las demás unidades aliadas ganan +1 Vida.',
    flavor: 'Guardián del bosque profundo, inmemorial.',
    keywords: ['guard'], collectorNumber: 38, aiTags: ['durable', 'buff'], unique: false,
    effects: [{ kind: 'passive', id: 'buff-allied-units-health', value: 1 }],
    vfx: { summonEffect: 'bear-roar', persistentEffect: 'forest-aura' },
  }),
  defineCard({
    id: 'arboleda-sagrada', name: 'Arboleda Sagrada', faction: 'nature', type: 'structure', subtype: 'Arboleda',
    rarity: 'rare', cost: factionCost('nature', 2, 1), resistance: 5,
    rules: 'Las unidades aliadas al entrar en juego ganan +1 Vida.',
    flavor: 'Tierra virgen donde todo florece con propósito.',
    keywords: [], collectorNumber: 39, aiTags: ['structure', 'buff'], unique: false,
    effects: [{ kind: 'passive', id: 'entry-allied-units-gain-health', value: 1 }],
    vfx: { summonEffect: 'forest-bloom', persistentEffect: 'growth-aura' },
  }),
  defineCard({
    id: 'crecimiento-salvaje', name: 'Crecimiento Salvaje', faction: 'nature', type: 'instant', subtype: 'Conjuro',
    rarity: 'uncommon', cost: factionCost('nature', 1, 2),
    rules: 'Una unidad aliada gana +2 Vida y +1 Ataque hasta fin de turno.',
    flavor: 'La naturaleza siempre encuentra la forma de crecer.',
    keywords: [], collectorNumber: 40, aiTags: ['buff', 'combat'], unique: false,
    effects: [
      { kind: 'passive', id: 'target-attack-until-end', value: 1 },
      { kind: 'passive', id: 'target-health-permanent', value: 2 },
    ],
    vfx: { impactEffect: 'vine-growth' },
  }),
  defineCard({
    id: 'centauro-cazador', name: 'Centauro Cazador', faction: 'nature', type: 'unit', subtype: 'Humanoid',
    rarity: 'uncommon', cost: factionCost('nature', 1, 2), attack: 3, health: 2, range: 2, movement: 2,
    rules: 'Perforar. Cuando ataca, todas las unidades aliadas adyacentes ganan +1 Ataque.',
    flavor: 'Corredor veloz de los prados dorados.',
    keywords: ['pierce'], collectorNumber: 41, aiTags: ['ranged', 'buff'], unique: false,
    effects: [{ kind: 'passive', id: 'attack-buff-nearby-allies', value: 1 }],
    vfx: { summonEffect: 'hooves-thunder', attackEffect: 'swift-charge' },
  }),
  defineCard({
    id: 'elfo-ancestral', name: 'Elfo Ancestral', faction: 'nature', type: 'unit', subtype: 'Humanoid',
    rarity: 'rare', cost: factionCost('nature', 2, 3), attack: 4, health: 3, range: 2, movement: 2,
    rules: 'Roba una carta cuando entra en juego. Tus instantes cuestan 1 genérico menos.',
    flavor: 'Antigua memoria viviente del primer bosque.',
    keywords: [], collectorNumber: 42, aiTags: ['finisher', 'draw'], unique: false,
    effects: [{ kind: 'draw', amount: 1 }, { kind: 'passive', id: 'instant-cost-discount', value: 1 }],
    vfx: { summonEffect: 'ancient-whisper', persistentEffect: 'elder-wisdom' },
  }),
  defineCard({
    id: 'guardian-robledal', name: 'Guardián del Robledal', faction: 'nature', type: 'unit', subtype: 'Treant',
    rarity: 'uncommon', cost: factionCost('nature', 2, 2), attack: 2, health: 5, range: 1, movement: 1,
    rules: 'La primera vez que recibe daño cada turno, lo reduce en 1.',
    flavor: 'Lleva tanto tiempo en pie que el bosque creció a su alrededor.',
    keywords: ['guard'], collectorNumber: 67, aiTags: ['durable', 'defense'], unique: false,
    effects: [{ kind: 'passive', id: 'first-damage-reduction', value: 1 }],
    vfx: { summonEffect: 'root-anchor', persistentEffect: 'bark-ward' },
  }),
  defineCard({
    id: 'driada-manantial', name: 'Dríade del Manantial', faction: 'nature', type: 'unit', subtype: 'Espíritu',
    rarity: 'common', cost: factionCost('nature', 1, 1), attack: 1, health: 3, range: 1, movement: 1,
    rules: 'Cuando entra en juego, tu Nexo recupera 3 de Vida.',
    flavor: 'El agua que custodia recuerda cómo era el mundo sin heridas.',
    keywords: [], collectorNumber: 68, aiTags: ['heal', 'support'], unique: false,
    effects: [{ kind: 'heal-nexus', amount: 3 }],
    vfx: { summonEffect: 'spring-bloom', persistentEffect: 'water-glow' },
  }),
  defineCard({
    id: 'jabali-embestida', name: 'Jabalí de Embestida', faction: 'nature', type: 'unit', subtype: 'Bestia',
    rarity: 'uncommon', cost: factionCost('nature', 2, 2), attack: 4, health: 3, range: 1, movement: 2,
    rules: 'Impulso y Golpe Veloz: puede moverse y atacar el turno en que entra en juego.',
    flavor: 'No rodea los obstáculos. Los convierte en astillas.',
    keywords: ['impulse', 'swift-strike'], collectorNumber: 69, aiTags: ['aggressive', 'fast'], unique: false,
    effects: [],
    vfx: { summonEffect: 'boar-snort', attackEffect: 'tusk-charge' },
  }),
  defineCard({
    id: 'savia-restauradora', name: 'Savia Restauradora', faction: 'nature', type: 'instant', subtype: 'Conjuro',
    rarity: 'uncommon', cost: factionCost('nature', 2, 1),
    rules: 'Tu Nexo recupera 5 de Vida y robas una carta.',
    flavor: 'La herida se cierra, pero el árbol recuerda el corte.',
    keywords: [], collectorNumber: 70, aiTags: ['heal', 'draw'], unique: false,
    effects: [{ kind: 'heal-nexus', amount: 5 }, { kind: 'draw', amount: 1 }],
    vfx: { impactEffect: 'golden-sap' },
  }),
  defineCard({
    id: 'muralla-zarzas', name: 'Muralla de Zarzas', faction: 'nature', type: 'structure', subtype: 'Barrera',
    rarity: 'uncommon', cost: factionCost('nature', 2, 1), resistance: 6,
    rules: 'Al alzarse, inflige 2 de daño a una unidad enemiga adyacente.',
    flavor: 'Crece más deprisa de lo que tarda un ejército en rodearla.',
    keywords: [], collectorNumber: 71, aiTags: ['defense', 'wall'], unique: false,
    effects: [{ kind: 'passive', id: 'entry-adjacent-enemy-damage', value: 2 }],
    vfx: { summonEffect: 'bramble-surge', persistentEffect: 'thorn-bristle' },
  }),
  defineCard({
    id: 'aliento-primavera', name: 'Aliento de Primavera', faction: 'nature', type: 'instant', subtype: 'Conjuro',
    rarity: 'rare', cost: factionCost('nature', 2, 2),
    rules: 'Una unidad aliada gana +3 de Ataque este turno y recupera su movimiento.',
    flavor: 'Basta un soplo tibio para que la rama muerta vuelva a empujar.',
    keywords: [], collectorNumber: 72, aiTags: ['buff', 'tempo'], unique: false,
    effects: [{ kind: 'passive', id: 'target-attack-until-end', value: 3 }, { kind: 'refresh-move' }],
    vfx: { impactEffect: 'spring-gust' },
  }),
];

const orderCards: readonly CardDefinition[] = [
  defineCard({
    id: 'fuente-orden', name: 'Fuente Orden', faction: 'order', type: 'mana', subtype: 'Fuente',
    rarity: 'common', cost: factionCost('order', 0),
    rules: 'Agota esta fuente: genera 1 de Esencia Soberana.',
    flavor: 'La ley perfecta grabada en cristal.',
    keywords: [], collectorNumber: 43, aiTags: ['resource'], unique: false, effects: [],
    vfx: { persistentEffect: 'order-source-light' }, sfx: { play: 'resource-order' },
  }),
  defineCard({
    id: 'angel-celestial', name: 'Ángel Celestial', faction: 'order', type: 'unit', subtype: 'Celestial',
    rarity: 'uncommon', cost: factionCost('order', 2, 1), attack: 3, health: 2, range: 2, movement: 1,
    rules: 'Vuelo y Vínculo vital. Cuando entra en juego, gana escudo preventivo 1.',
    flavor: 'Mensajero de la justicia eternal.',
    keywords: ['flying', 'lifelink'], collectorNumber: 44, aiTags: ['defense', 'ranged'], unique: false,
    effects: [{ kind: 'passive', id: 'entry-shield-gain', value: 1 }],
    vfx: { summonEffect: 'heavenly-descent', persistentEffect: 'holy-light' },
  }),
  defineCard({
    id: 'aguila-celestial', name: 'Águila Celestial', faction: 'order', type: 'unit', subtype: 'Ave',
    rarity: 'common', cost: factionCost('order', 1, 2), attack: 2, health: 2, range: 2, movement: 2,
    rules: 'Vuelo. Puede atacar sin ser tocada por unidades terrestres.',
    flavor: 'Sus ojos vigilan desde las alturas.',
    keywords: ['flying'], collectorNumber: 45, aiTags: ['ranged', 'evasion'], unique: false, effects: [],
    vfx: { summonEffect: 'eagle-cry', attackEffect: 'dive-strike' },
  }),
  defineCard({
    id: 'pegaso-celestial', name: 'Pégaso Celestial', faction: 'order', type: 'unit', subtype: 'Bestia',
    rarity: 'rare', cost: factionCost('order', 2, 2), attack: 3, health: 3, range: 2, movement: 2,
    rules: 'Vuelo e impulso. Al atacar por primera vez, regenera 2 Vida.',
    flavor: 'Símbolo de libertad y nobleza sin fin.',
    keywords: ['flying', 'impulse'], collectorNumber: 46, aiTags: ['ranged', 'durable'], unique: false,
    effects: [{ kind: 'passive', id: 'first-attack-heal', value: 2 }],
    vfx: { summonEffect: 'winged-gallop', attackEffect: 'aerial-strike' },
  }),
  defineCard({
    id: 'paladin-glorioso', name: 'Paladín Glorioso', faction: 'order', type: 'unit', subtype: 'Humanoid',
    rarity: 'rare', cost: factionCost('order', 2, 3), attack: 4, health: 3, range: 1, movement: 1, resistance: 3,
    rules: 'Las unidades aliadas adyacentes no pueden ser congeladas.',
    flavor: 'Campeón de la fe que nunca retrocede.',
    keywords: ['guard'], collectorNumber: 47, aiTags: ['defense', 'protection'], unique: false,
    effects: [{ kind: 'passive', id: 'protect-adjacent-from-freeze' }],
    vfx: { summonEffect: 'divine-oath', persistentEffect: 'holy-protection' },
  }),
  defineCard({
    id: 'clerigo-luz', name: 'Clérigo de Luz', faction: 'order', type: 'unit', subtype: 'Humanoid',
    rarity: 'uncommon', cost: factionCost('order', 1, 1), attack: 1, health: 3, range: 2, movement: 1,
    rules: 'Las unidades aliadas al entrar en juego ganan +1 Vida.',
    flavor: 'Su presencia sana las heridas más profundas.',
    keywords: [], collectorNumber: 48, aiTags: ['healer', 'support'], unique: false,
    effects: [{ kind: 'passive', id: 'entry-allied-units-gain-health', value: 1 }],
    vfx: { summonEffect: 'healing-light', persistentEffect: 'blessed-aura' },
  }),
  defineCard({
    id: 'grifo-orden', name: 'Grifo de Orden', faction: 'order', type: 'unit', subtype: 'Bestia',
    rarity: 'uncommon', cost: factionCost('order', 2, 2), attack: 3, health: 3, range: 2, movement: 2,
    rules: 'Vigilancia. Las unidades enemigas adyacentes tienen -1 Ataque.',
    flavor: 'Guardián que previene todo caos y desorden.',
    keywords: ['guard'], collectorNumber: 49, aiTags: ['defense', 'control'], unique: false,
    effects: [{ kind: 'passive', id: 'weaken-adjacent-enemies', value: 1 }],
    vfx: { summonEffect: 'guardian-roar', persistentEffect: 'ward-aura' },
  }),
  defineCard({
    id: 'juicio-divino', name: 'Juicio Divino', faction: 'order', type: 'instant', subtype: 'Conjuro',
    rarity: 'rare', cost: factionCost('order', 1, 3),
    rules: 'Destruye una unidad enemiga con 2 Vida o menos. Gana 2 Vida.',
    flavor: 'La verdad juzga a todos sin piedad.',
    keywords: [], collectorNumber: 50, aiTags: ['removal', 'healing'], unique: false,
    effects: [{ kind: 'damage', amount: 99, target: 'enemy-piece' }, { kind: 'heal-nexus', amount: 2 }],
    vfx: { impactEffect: 'divine-judgment' },
  }),
  defineCard({
    id: 'lancero-alba', name: 'Lancero del Alba', faction: 'order', type: 'unit', subtype: 'Soldado',
    rarity: 'common', cost: factionCost('order', 1, 1), attack: 2, health: 3, range: 1, movement: 1,
    rules: 'La primera vez que recibe daño cada turno, lo reduce en 1.',
    flavor: 'Aguanta la línea hasta que el sol termine de salir.',
    keywords: ['guard'], collectorNumber: 73, aiTags: ['defense', 'durable'], unique: false,
    effects: [{ kind: 'passive', id: 'first-damage-reduction', value: 1 }],
    vfx: { summonEffect: 'dawn-muster', persistentEffect: 'shield-brace' },
  }),
  defineCard({
    id: 'bastion-marmoreo', name: 'Bastión Marmóreo', faction: 'order', type: 'structure', subtype: 'Fortaleza',
    rarity: 'rare', cost: factionCost('order', 2, 2), resistance: 7,
    rules: 'Muro de mármol y oro que no cede terreno.',
    flavor: 'Han caído tres reinos desde que se puso la primera piedra.',
    keywords: [], collectorNumber: 74, aiTags: ['defense', 'wall'], unique: false,
    effects: [],
    vfx: { summonEffect: 'marble-rise', persistentEffect: 'gold-sigil-glow' },
  }),
  defineCard({
    id: 'centinela-solar', name: 'Centinela Solar', faction: 'order', type: 'unit', subtype: 'Constructo',
    rarity: 'uncommon', cost: factionCost('order', 2, 2), attack: 3, health: 4, range: 2, movement: 1,
    rules: 'Aturdir: la unidad que golpea no podrá atacar en su próximo turno.',
    flavor: 'No duerme, no parpadea, no pregunta.',
    keywords: ['stun'], collectorNumber: 75, aiTags: ['ranged', 'defense'], unique: false,
    effects: [],
    vfx: { summonEffect: 'solar-ignite', attackEffect: 'sun-lance' },
  }),
  defineCard({
    id: 'bendicion-escudo', name: 'Bendición del Escudo', faction: 'order', type: 'instant', subtype: 'Conjuro',
    rarity: 'common', cost: factionCost('order', 1, 1),
    rules: 'Tu Nexo recupera 4 de Vida.',
    flavor: 'La luz no detiene el golpe: repara lo que el golpe rompió.',
    keywords: [], collectorNumber: 76, aiTags: ['heal'], unique: false,
    effects: [{ kind: 'heal-nexus', amount: 4 }],
    vfx: { impactEffect: 'shield-blessing' },
  }),
  defineCard({
    id: 'heraldo-juicio', name: 'Heraldo del Juicio', faction: 'order', type: 'unit', subtype: 'Celestial',
    rarity: 'rare', cost: factionCost('order', 2, 3), attack: 4, health: 3, range: 1, movement: 2,
    rules: 'Aturdir. Al entrar en juego, inflige 2 de daño a una unidad enemiga adyacente.',
    flavor: 'Aterriza una sola vez, y con eso basta.',
    keywords: ['stun'], collectorNumber: 77, aiTags: ['removal', 'finisher'], unique: false,
    effects: [{ kind: 'passive', id: 'entry-adjacent-enemy-damage', value: 2 }],
    vfx: { summonEffect: 'judgment-descent', attackEffect: 'hammer-fall' },
  }),
  defineCard({
    id: 'columna-luz', name: 'Columna de Luz', faction: 'order', type: 'instant', subtype: 'Conjuro',
    rarity: 'uncommon', cost: factionCost('order', 2, 2),
    rules: 'Inflige 5 de daño a una pieza enemiga.',
    flavor: 'El cielo se abre, señala, y cierra.',
    keywords: [], collectorNumber: 78, aiTags: ['removal', 'damage'], unique: false,
    effects: [{ kind: 'damage', amount: 5, target: 'enemy-piece' }],
    vfx: { impactEffect: 'light-pillar' },
  }),
];

const shadowCards: readonly CardDefinition[] = [
  defineCard({
    id: 'fuente-sombra', name: 'Fuente Sombra', faction: 'shadow', type: 'mana', subtype: 'Fuente',
    rarity: 'common', cost: factionCost('shadow', 0),
    rules: 'Agota esta fuente: genera 1 de Esencia Oscura.',
    flavor: 'Poder extraído de la eternidad silenciosa.',
    keywords: [], collectorNumber: 51, aiTags: ['resource'], unique: false, effects: [],
    vfx: { persistentEffect: 'shadow-source-drain' }, sfx: { play: 'resource-shadow' },
  }),
  defineCard({
    id: 'murcielago-sombra', name: 'Murciélago Sombra', faction: 'shadow', type: 'unit', subtype: 'Bestia',
    rarity: 'common', cost: factionCost('shadow', 1, 1), attack: 1, health: 2, range: 1, movement: 2,
    rules: 'Vuelo. Cuando ataca, drena 1 Vida al enemigo para ti.',
    flavor: 'Drenador silencioso de la noche profunda.',
    keywords: ['flying'], collectorNumber: 52, aiTags: ['lifedrain', 'evasion'], unique: false,
    effects: [{ kind: 'passive', id: 'drain-life-on-attack', value: 1 }],
    vfx: { summonEffect: 'shadow-wings', attackEffect: 'life-drain' },
  }),
  defineCard({
    id: 'espectro-siniestro', name: 'Espectro Siniestro', faction: 'shadow', type: 'unit', subtype: 'Espíritu',
    rarity: 'uncommon', cost: factionCost('shadow', 1, 2), attack: 2, health: 2, range: 1, movement: 2,
    rules: 'Incorporal. No puede ser bloqueado. Cuando daña, descarta una carta enemiga.',
    flavor: 'Alma atrapada entre mundos, hambrienta.',
    keywords: [], collectorNumber: 53, aiTags: ['evasion', 'discard'], unique: false,
    effects: [{ kind: 'passive', id: 'unblockable-ghost' }, { kind: 'passive', id: 'discard-enemy-on-damage', value: 1 }],
    vfx: { summonEffect: 'ghostly-wail', attackEffect: 'spectral-touch' },
  }),
  defineCard({
    id: 'esqueleto-guerrero', name: 'Esqueleto Guerrero', faction: 'shadow', type: 'unit', subtype: 'Undead',
    rarity: 'common', cost: factionCost('shadow', 1, 1), attack: 2, health: 2, range: 1, movement: 1,
    rules: 'Cuando muere, puede resucitar gastando 2 de Esencia Oscura.',
    flavor: 'Soldado que no conoce el verdadero reposo.',
    keywords: [], collectorNumber: 54, aiTags: ['undead', 'sacrifice'], unique: false,
    effects: [{ kind: 'passive', id: 'undead-resurrection', value: 2 }],
    vfx: { summonEffect: 'bone-rattle', deathEffect: 'bone-scatter' },
  }),
  defineCard({
    id: 'nigromante-oscuro', name: 'Nigromante Oscuro', faction: 'shadow', type: 'unit', subtype: 'Humanoid',
    rarity: 'rare', cost: factionCost('shadow', 2, 2), attack: 3, health: 2, range: 2, movement: 1,
    rules: 'Cuando una unidad aliada muere, roba una carta. Tus hechizos drenan Vida.',
    flavor: 'Maestro que reescribe el destino de los muertos.',
    keywords: [], collectorNumber: 55, aiTags: ['finisher', 'draw'], unique: false,
    effects: [{ kind: 'passive', id: 'draw-on-ally-death', value: 1 }, { kind: 'passive', id: 'drain-spells', value: 1 }],
    vfx: { summonEffect: 'death-magic', persistentEffect: 'curse-aura' },
  }),
  defineCard({
    id: 'maldicion-sombra', name: 'Maldición Sombra', faction: 'shadow', type: 'instant', subtype: 'Encantamiento',
    rarity: 'uncommon', cost: factionCost('shadow', 1, 2),
    rules: 'Una unidad enemiga pierde 1 Vida al final de cada turno.',
    flavor: 'Marca invisible que consume vitalidad.',
    keywords: [], collectorNumber: 56, aiTags: ['control', 'damage'], unique: false,
    effects: [{ kind: 'passive', id: 'curse-drain-health', value: 1 }],
    vfx: { impactEffect: 'curse-mark', persistentEffect: 'drain-aura' },
  }),
  defineCard({
    id: 'vampiro-siniestro', name: 'Vampiro Siniestro', faction: 'shadow', type: 'unit', subtype: 'Humanoid',
    rarity: 'uncommon', cost: factionCost('shadow', 2, 1), attack: 3, health: 2, range: 1, movement: 2,
    rules: 'Vínculo vital: el daño que reparte cura tu Nexo en la misma cantidad.',
    flavor: 'Inmortal que se alimenta de desesperación.',
    keywords: ['lifelink'], collectorNumber: 57, aiTags: ['lifedrain', 'aggressive'], unique: false,
    effects: [],
    vfx: { summonEffect: 'vampire-rise', attackEffect: 'blood-drain' },
  }),
  defineCard({
    id: 'pesadilla-mortal', name: 'Pesadilla Mortal', faction: 'shadow', type: 'unit', subtype: 'Horror',
    rarity: 'rare', cost: factionCost('shadow', 2, 3), attack: 4, health: 3, range: 1, movement: 1,
    rules: 'Cuando entra en juego, descarta 2 cartas enemigas. Esas unidades pierden -1 Vida.',
    flavor: 'Terror que consume cordura y esperanza.',
    keywords: [], collectorNumber: 58, aiTags: ['finisher', 'discard'], unique: false,
    effects: [{ kind: 'discard', amount: 2, target: 'enemy-hand' }, { kind: 'passive', id: 'discarded-units-weaken', value: 1 }],
    vfx: { summonEffect: 'nightmare-rise', persistentEffect: 'dread-aura' },
  }),
  defineCard({
    id: 'sabueso-tumba', name: 'Sabueso de la Tumba', faction: 'shadow', type: 'unit', subtype: 'Undead',
    rarity: 'common', cost: factionCost('shadow', 1, 1), attack: 3, health: 1, range: 1, movement: 2,
    rules: 'Impulso y Golpe Veloz: puede moverse y atacar el turno en que entra en juego.',
    flavor: 'Ya no caza para comer. Caza porque no sabe parar.',
    keywords: ['impulse', 'swift-strike'], collectorNumber: 79, aiTags: ['aggressive', 'fast'], unique: false,
    effects: [],
    vfx: { summonEffect: 'grave-howl', attackEffect: 'bone-lunge' },
  }),
  defineCard({
    id: 'sacerdote-carrona', name: 'Sacerdote de la Carroña', faction: 'shadow', type: 'unit', subtype: 'Humanoid',
    rarity: 'uncommon', cost: factionCost('shadow', 1, 2), attack: 2, health: 3, range: 1, movement: 1,
    rules: 'Al entrar en juego, descartas una carta y robas una carta.',
    flavor: 'Cambia lo que ya no sirve por lo que aún puede doler.',
    keywords: [], collectorNumber: 80, aiTags: ['draw', 'discard'], unique: false,
    effects: [{ kind: 'draw', amount: 1 }, { kind: 'discard', amount: 1 }],
    vfx: { summonEffect: 'carrion-rite', persistentEffect: 'censer-smoke' },
  }),
  defineCard({
    id: 'ritual-sanguino', name: 'Ritual Sanguino', faction: 'shadow', type: 'instant', subtype: 'Ritual',
    rarity: 'uncommon', cost: factionCost('shadow', 1, 1),
    rules: 'Tu Nexo recupera 4 de Vida y descartas una carta.',
    flavor: 'Toda vida devuelta se cobra en otra parte.',
    keywords: [], collectorNumber: 81, aiTags: ['heal', 'discard'], unique: false,
    effects: [{ kind: 'heal-nexus', amount: 4 }, { kind: 'discard', amount: 1 }],
    vfx: { impactEffect: 'blood-sigil' },
  }),
  defineCard({
    id: 'cripta-olvidada', name: 'Cripta Olvidada', faction: 'shadow', type: 'structure', subtype: 'Mausoleo',
    rarity: 'rare', cost: factionCost('shadow', 2, 1), resistance: 5,
    rules: 'Tus hechizos cuestan 1 genérico menos.',
    flavor: 'Nadie recuerda quién yace dentro. Ella sí recuerda a todos.',
    keywords: [], collectorNumber: 82, aiTags: ['ramp', 'defense'], unique: false,
    effects: [{ kind: 'passive', id: 'spell-generic-discount', value: 1 }],
    vfx: { summonEffect: 'crypt-open', persistentEffect: 'wisp-leak' },
  }),
  defineCard({
    id: 'guadana-espectral', name: 'Guadaña Espectral', faction: 'shadow', type: 'instant', subtype: 'Conjuro',
    rarity: 'rare', cost: factionCost('shadow', 2, 2),
    rules: 'Inflige 4 de daño a una pieza enemiga y 2 a la unidad enemiga más débil.',
    flavor: 'El primer corte se ve venir. El segundo ya está dado.',
    keywords: [], collectorNumber: 83, aiTags: ['removal', 'damage'], unique: false,
    effects: [
      { kind: 'damage', amount: 4, target: 'enemy-piece' },
      { kind: 'splash-weakest-enemy', amount: 2 },
    ],
    vfx: { impactEffect: 'spectral-reap' },
  }),
  defineCard({
    id: 'senor-osario', name: 'Señor del Osario', faction: 'shadow', type: 'unit', subtype: 'Undead',
    rarity: 'mythic', cost: factionCost('shadow', 3, 3), attack: 5, health: 4, range: 1, movement: 1,
    rules: 'Vínculo vital. Al entrar en juego, inflige 2 de daño a todas las unidades enemigas adyacentes.',
    flavor: 'Su trono creció solo, hueso a hueso, mientras él esperaba sentado.',
    keywords: ['lifelink'], collectorNumber: 84, aiTags: ['finisher', 'removal'], unique: false,
    effects: [{ kind: 'adjacent-damage', amount: 2, includeAllies: false }],
    vfx: { summonEffect: 'ossuary-throne', attackEffect: 'necrotic-cleave' },
  }),
];

const voidCards: readonly CardDefinition[] = [
  defineCard({
    id: 'fuente-vacio', name: 'Fuente Vacío', faction: 'void', type: 'mana', subtype: 'Fuente',
    rarity: 'common', cost: factionCost('void', 0),
    rules: 'Agota esta fuente: genera 1 de Esencia Distorsionada.',
    flavor: 'Energía que rompió los límites del espacio.',
    keywords: [], collectorNumber: 59, aiTags: ['resource'], unique: false, effects: [],
    vfx: { persistentEffect: 'void-source-distortion' }, sfx: { play: 'resource-void' },
  }),
  defineCard({
    id: 'basilisco-caos', name: 'Basilisco del Caos', faction: 'void', type: 'unit', subtype: 'Bestia',
    rarity: 'uncommon', cost: factionCost('void', 2, 1), attack: 2, health: 3, range: 2, movement: 1,
    rules: 'Gaze mortal. Cuando ataca, sujeta a la unidad objetivo por 1 turno.',
    flavor: 'Criatura que distorsiona la realidad a su paso.',
    keywords: [], collectorNumber: 60, aiTags: ['control', 'ranged'], unique: false,
    effects: [{ kind: 'freeze', duration: 1 }],
    vfx: { summonEffect: 'chaos-roar', attackEffect: 'petrifying-gaze' },
  }),
  defineCard({
    id: 'quimera-caos', name: 'Quimera del Caos', faction: 'void', type: 'unit', subtype: 'Horror',
    rarity: 'uncommon', cost: factionCost('void', 2, 2), attack: 3, health: 3, range: 2, movement: 2,
    rules: 'Cuando entra en juego, si hay una unidad aliada adyacente, copia su Ataque como bono permanente.',
    flavor: 'Abominación que es todo y nada a la vez.',
    keywords: [], collectorNumber: 61, aiTags: ['synergy', 'shapeshifter'], unique: false,
    effects: [{ kind: 'passive', id: 'copy-adjacent-attack' }],
    vfx: { summonEffect: 'chimera-morph', persistentEffect: 'chaos-aura' },
  }),
  defineCard({
    id: 'devorador-entropico', name: 'Devorador Entrópico', faction: 'void', type: 'unit', subtype: 'Horror',
    rarity: 'rare', cost: factionCost('void', 2, 2), attack: 3, health: 4, range: 1, movement: 1, resistance: 2,
    rules: 'Perforar. Cuando una estructura es destruida, drena su Resistencia como Vida.',
    flavor: 'Entidad que consume orden y estructura.',
    keywords: ['pierce'], collectorNumber: 62, aiTags: ['durable', 'structure-tech'], unique: false,
    effects: [{ kind: 'passive', id: 'devour-structure-resistance' }],
    vfx: { summonEffect: 'entropy-birth', persistentEffect: 'corruption-aura' },
  }),
  defineCard({
    id: 'leviatan-abismal', name: 'Leviatán Abismal', faction: 'void', type: 'unit', subtype: 'Bestia',
    rarity: 'mythic', cost: factionCost('void', 3, 4), attack: 6, health: 5, range: 1, movement: 1,
    rules: 'Impulso. Cuando ataca, empuja 1 casilla hacia atrás a las unidades enemigas adyacentes al objetivo.',
    flavor: 'Horror primordial del vacío sin fondo.',
    keywords: ['impulse'], collectorNumber: 63, aiTags: ['finisher', 'control'], unique: true,
    effects: [{ kind: 'passive', id: 'push-adjacent-enemies-on-attack' }],
    vfx: { summonEffect: 'leviathan-awaken', attackEffect: 'void-collapse', deathEffect: 'reality-break' },
  }),
  defineCard({
    id: 'aniquilacion-vacio', name: 'Aniquilación del Vacío', faction: 'void', type: 'instant', subtype: 'Conjuro',
    rarity: 'rare', cost: factionCost('void', 2, 3),
    rules: 'Destruye todas las estructuras enemigas. Gana Esencia igual a su Resistencia.',
    flavor: 'El final de todas las cosas.',
    keywords: [], collectorNumber: 64, aiTags: ['removal', 'board-wipe'], unique: false,
    effects: [{ kind: 'destroy-all-enemy-structures', gainEssencePerResistance: true }],
    vfx: { impactEffect: 'void-annihilation' },
  }),
  defineCard({
    id: 'paradoja-vacio', name: 'Paradoja del Vacío', faction: 'void', type: 'instant', subtype: 'Portal',
    rarity: 'uncommon', cost: factionCost('void', 1, 3),
    rules: 'Una vez por turno, una unidad aliada puede cambiar de lado de forma temporal.',
    flavor: 'Puerta a realidades que se contradicen.',
    keywords: [], collectorNumber: 65, aiTags: ['movement', 'control'], unique: false,
    effects: [{ kind: 'refresh-move' }],
    vfx: { impactEffect: 'paradox-portal', persistentEffect: 'reality-rift' },
  }),
  defineCard({
    id: 'horror-abisal', name: 'Horror Abisal', faction: 'void', type: 'unit', subtype: 'Horror',
    rarity: 'uncommon', cost: factionCost('void', 1, 2), attack: 2, health: 2, range: 2, movement: 1,
    rules: 'Cuando ataca, todas las unidades enemigas pierden 1 Movimiento este turno.',
    flavor: 'Presencia que congela la voluntad de actuar.',
    keywords: [], collectorNumber: 66, aiTags: ['control', 'ranged'], unique: false,
    effects: [{ kind: 'passive', id: 'slow-enemies-on-attack', value: 1 }],
    vfx: { summonEffect: 'horror-screech', attackEffect: 'dread-beam' },
  }),
  defineCard({
    id: 'heraldo-fractura', name: 'Heraldo de la Fractura', faction: 'void', type: 'unit', subtype: 'Horror',
    rarity: 'common', cost: factionCost('void', 1, 1), attack: 2, health: 2, range: 1, movement: 2,
    rules: 'Impulso. Al entrar en juego, inflige 1 de daño a una unidad enemiga adyacente.',
    flavor: 'No cruza la grieta: la grieta lo deja donde ya quería estar.',
    keywords: ['impulse'], collectorNumber: 85, aiTags: ['aggressive', 'fast'], unique: false,
    effects: [{ kind: 'passive', id: 'entry-adjacent-enemy-damage', value: 1 }],
    vfx: { summonEffect: 'rift-step', attackEffect: 'shard-lash' },
  }),
  defineCard({
    id: 'portal-inestable', name: 'Portal Inestable', faction: 'void', type: 'structure', subtype: 'Portal',
    rarity: 'uncommon', cost: factionCost('void', 1, 1), resistance: 4,
    rules: 'La primera vez que recibe daño cada turno, lo reduce en 1.',
    flavor: 'Lo sujetan seis monolitos. Uno ya se está resquebrajando.',
    keywords: [], collectorNumber: 86, aiTags: ['defense', 'utility'], unique: false,
    effects: [{ kind: 'passive', id: 'first-damage-reduction', value: 1 }],
    vfx: { summonEffect: 'portal-tear', persistentEffect: 'unstable-arc' },
  }),
  defineCard({
    id: 'caminante-umbral', name: 'Caminante del Umbral', faction: 'void', type: 'unit', subtype: 'Horror',
    rarity: 'uncommon', cost: factionCost('void', 2, 1), attack: 3, health: 3, range: 1, movement: 2,
    rules: 'Golpe Veloz: puede atacar el turno en que entra en juego.',
    flavor: 'Llega antes de haber salido.',
    keywords: ['swift-strike'], collectorNumber: 87, aiTags: ['aggressive', 'evasion'], unique: false,
    effects: [],
    vfx: { summonEffect: 'threshold-blink', attackEffect: 'violet-edge' },
  }),
  defineCard({
    id: 'colapso-dimensional', name: 'Colapso Dimensional', faction: 'void', type: 'instant', subtype: 'Conjuro',
    rarity: 'rare', cost: factionCost('void', 2, 2),
    rules: 'Inflige 3 de daño a una pieza y 3 a la unidad enemiga más débil.',
    flavor: 'El espacio se arruga como papel y arrastra lo que había encima.',
    keywords: [], collectorNumber: 88, aiTags: ['removal', 'damage'], unique: false,
    effects: [
      { kind: 'damage', amount: 3, target: 'any-piece' },
      { kind: 'splash-weakest-enemy', amount: 3 },
    ],
    vfx: { impactEffect: 'dimensional-collapse' },
  }),
  defineCard({
    id: 'tejedor-entropia', name: 'Tejedor de Entropía', faction: 'void', type: 'unit', subtype: 'Humanoid',
    rarity: 'rare', cost: factionCost('void', 2, 2), attack: 2, health: 4, range: 2, movement: 1,
    rules: 'Tus hechizos cuestan 1 genérico menos.',
    flavor: 'Teje con hilos de lo que todavía no ha pasado.',
    keywords: [], collectorNumber: 89, aiTags: ['ramp', 'ranged'], unique: false,
    effects: [{ kind: 'passive', id: 'spell-generic-discount', value: 1 }],
    vfx: { summonEffect: 'loom-weave', persistentEffect: 'probability-threads' },
  }),
  defineCard({
    id: 'singularidad', name: 'Singularidad', faction: 'void', type: 'instant', subtype: 'Conjuro',
    rarity: 'uncommon', cost: factionCost('void', 1, 2),
    rules: 'Congela una unidad enemiga durante 2 turnos y le inflige 2 de daño.',
    flavor: 'Dentro de la esfera todo sigue cayendo. Fuera, nada se mueve.',
    keywords: [], collectorNumber: 90, aiTags: ['control', 'freeze'], unique: false,
    effects: [{ kind: 'freeze', duration: 2 }, { kind: 'damage', amount: 2, target: 'enemy-piece' }],
    vfx: { impactEffect: 'singularity-halt' },
  }),
];

/**
 * NEX-02 «Fractura»: la segunda oleada.
 *
 * Cuatro cartas por facción, elegidas para tapar el agujero de cada una: Furia
 * no tenía cierre tardío, Arcano no negaba turnos, Naturaleza no recuperaba
 * Vida, Orden no castigaba en masa, Sombra no tocaba la mano del rival y Vacío
 * no movía el tablero. Estrena tres mecánicas: mantenimiento de estructuras
 * («al final de tu turno»), disparador de muerte y palabras clave prestadas.
 */
const secondWaveCards: readonly CardDefinition[] = [
  // --- Furia ---
  defineCard({
    id: 'coloso-de-escoria', name: 'Coloso de Escoria', faction: 'fury', type: 'unit', subtype: 'Gigante',
    rarity: 'mythic', cost: factionCost('fury', 2, 4), attack: 8, health: 8, range: 1, movement: 1,
    rules: 'Perforar. Al entrar en juego, inflige 2 de daño a todas las unidades enemigas.',
    flavor: 'La Caldera no forja soldados: forja consecuencias.',
    keywords: ['pierce'], collectorNumber: 91, aiTags: ['finisher', 'area-damage'], unique: true,
    effects: [{ kind: 'damage-all-enemies', amount: 2 }],
    vfx: { summonEffect: 'caldera-eruption', attackEffect: 'siege-charge', impactEffect: 'stone-shockwave' },
    set: SECOND_WAVE_SET,
  }),
  defineCard({
    id: 'lanza-de-obsidiana', name: 'Lanza de Obsidiana', faction: 'fury', type: 'instant', subtype: 'Conjuro',
    rarity: 'uncommon', cost: factionCost('fury', 1, 1),
    rules: 'Inflige 5 de daño a una unidad enemiga. Tu Nexo se cura 2.',
    flavor: 'Se lanza una vez. No hace falta más.',
    keywords: [], collectorNumber: 92, aiTags: ['removal', 'damage'], unique: false,
    effects: [{ kind: 'damage', amount: 5, target: 'enemy-piece' }, { kind: 'heal-nexus', amount: 2 }],
    vfx: { impactEffect: 'obsidian-lance' },
    set: SECOND_WAVE_SET,
  }),
  defineCard({
    id: 'pira-de-los-caidos', name: 'Pira de los Caídos', faction: 'fury', type: 'structure', subtype: 'Pira',
    rarity: 'rare', cost: factionCost('fury', 1, 2), resistance: 5,
    rules: 'Al final de tu turno, inflige 1 de daño a la unidad enemiga más débil.',
    flavor: 'Arde por los que ya no pueden arder.',
    keywords: [], collectorNumber: 93, aiTags: ['structure', 'damage'], unique: false,
    effects: [{ kind: 'passive', id: 'upkeep-splash-weakest-enemy', value: 1 }],
    vfx: { summonEffect: 'forge-rise', persistentEffect: 'forge-glow', impactEffect: 'ember-oath' },
    set: SECOND_WAVE_SET,
  }),
  defineCard({
    id: 'heraldo-de-la-ruina', name: 'Heraldo de la Ruina', faction: 'fury', type: 'unit', subtype: 'Guerrero',
    rarity: 'rare', cost: factionCost('fury', 1, 2), attack: 4, health: 3, range: 1, movement: 2,
    rules: 'Golpe veloz. Cuando ataca, gana +1 de Ataque hasta el final del turno.',
    flavor: 'Cada golpe le enseña dónde duele el siguiente.',
    keywords: ['swift-strike'], collectorNumber: 94, aiTags: ['aggressive', 'combat'], unique: false,
    effects: [{ kind: 'buff-self-on-attack', attack: 1 }],
    vfx: { summonEffect: 'slag-sparks', attackEffect: 'cinder-dash', impactEffect: 'heavy-impact' },
    set: SECOND_WAVE_SET,
  }),

  // --- Arcano ---
  defineCard({
    id: 'custodio-del-solsticio', name: 'Custodio del Solsticio', faction: 'arcane', type: 'unit', subtype: 'Constructo',
    rarity: 'mythic', cost: factionCost('arcane', 2, 3), attack: 5, health: 7, range: 2, movement: 1,
    rules: 'Guardia. Al entrar en juego, congela 2 turnos a la unidad enemiga con más Ataque.',
    flavor: 'Cuenta los días que faltan para que vuelva la luz. Nunca se equivoca.',
    keywords: ['guard'], collectorNumber: 95, aiTags: ['defense', 'freeze'], unique: true,
    effects: [{ kind: 'freeze', duration: 2 }],
    vfx: { summonEffect: 'prism-rise', impactEffect: 'frost-lock', persistentEffect: 'solstice-halo' },
    set: SECOND_WAVE_SET,
  }),
  defineCard({
    id: 'silencio-prismatico', name: 'Silencio Prismático', faction: 'arcane', type: 'instant', subtype: 'Encantamiento',
    rarity: 'rare', cost: factionCost('arcane', 1, 1),
    rules: 'Aturde a una unidad enemiga y robas 1 carta.',
    flavor: 'No apaga el sonido: lo guarda para más tarde.',
    keywords: [], collectorNumber: 96, aiTags: ['control', 'draw'], unique: false,
    effects: [{ kind: 'stun' }, { kind: 'draw', amount: 1 }],
    vfx: { impactEffect: 'stun-daze' },
    set: SECOND_WAVE_SET,
  }),
  defineCard({
    id: 'garza-de-escarcha', name: 'Garza de Escarcha', faction: 'arcane', type: 'unit', subtype: 'Ave',
    rarity: 'uncommon', cost: factionCost('arcane', 1, 1), attack: 2, health: 3, range: 1, movement: 3,
    rules: 'Volador. Al entrar en juego, escruta 1.',
    flavor: 'Pesca en el reflejo, no en el agua.',
    keywords: ['flying'], collectorNumber: 97, aiTags: ['fast', 'utility'], unique: false,
    effects: [{ kind: 'scry', amount: 1 }],
    vfx: { summonEffect: 'frost-feathers', attackEffect: 'ice-dart' },
    set: SECOND_WAVE_SET,
  }),
  defineCard({
    id: 'biblioteca-sumergida', name: 'Biblioteca Sumergida', faction: 'arcane', type: 'structure', subtype: 'Archivo',
    rarity: 'rare', cost: factionCost('arcane', 1, 2), resistance: 6,
    rules: 'Tus hechizos cuestan 1 genérico menos. Al final de tu turno, si tienes 5 cartas o menos en la mano, robas 1.',
    flavor: 'Los libros siguen ahí. Solo hay que aprender a leer bajo el agua.',
    keywords: [], collectorNumber: 98, aiTags: ['structure', 'ramp', 'draw'], unique: false,
    effects: [
      { kind: 'passive', id: 'spell-generic-discount', value: 1 },
      { kind: 'passive', id: 'upkeep-draw-if-low', value: 1 },
    ],
    vfx: { summonEffect: 'tower-raise', persistentEffect: 'submerged-glow' },
    set: SECOND_WAVE_SET,
  }),

  // --- Naturaleza ---
  defineCard({
    id: 'ancestro-del-bosque', name: 'Ancestro del Bosque', faction: 'nature', type: 'unit', subtype: 'Treant',
    rarity: 'mythic', cost: factionCost('nature', 2, 4), attack: 6, health: 9, range: 1, movement: 1,
    rules: 'Guardia. Al entrar en juego, cura 4 a tu Nexo.',
    flavor: 'Lleva tanto tiempo de pie que el bosque creció a su alrededor por respeto.',
    keywords: ['guard'], collectorNumber: 99, aiTags: ['defense', 'heal'], unique: true,
    effects: [{ kind: 'heal-nexus', amount: 4 }],
    vfx: { summonEffect: 'root-surge', persistentEffect: 'ancient-bark' },
    set: SECOND_WAVE_SET,
  }),
  defineCard({
    id: 'manada-en-celo', name: 'Manada en Celo', faction: 'nature', type: 'instant', subtype: 'Conjuro',
    rarity: 'uncommon', cost: factionCost('nature', 1, 1),
    rules: 'Una unidad aliada gana +2 de Ataque hasta el final del turno y puede volver a moverse.',
    flavor: 'La estación no pregunta si es buen momento.',
    keywords: [], collectorNumber: 100, aiTags: ['buff', 'combat'], unique: false,
    effects: [{ kind: 'passive', id: 'target-attack-until-end', value: 2 }, { kind: 'refresh-move' }],
    vfx: { impactEffect: 'wild-rush' },
    set: SECOND_WAVE_SET,
  }),
  defineCard({
    id: 'corazon-del-manantial', name: 'Corazón del Manantial', faction: 'nature', type: 'structure', subtype: 'Manantial',
    rarity: 'rare', cost: factionCost('nature', 1, 1), resistance: 6,
    rules: 'Al final de tu turno, cura 2 a tu Nexo.',
    flavor: 'Mana desde antes de que hubiera nadie con sed.',
    keywords: [], collectorNumber: 101, aiTags: ['structure', 'heal'], unique: false,
    effects: [{ kind: 'passive', id: 'upkeep-heal-nexus', value: 2 }],
    vfx: { summonEffect: 'spring-bloom', persistentEffect: 'living-water' },
    set: SECOND_WAVE_SET,
  }),
  defineCard({
    id: 'guardabosques-tenaz', name: 'Guardabosques Tenaz', faction: 'nature', type: 'unit', subtype: 'Humanoide',
    rarity: 'common', cost: factionCost('nature', 1, 1), attack: 3, health: 4, range: 2, movement: 1,
    rules: 'Vínculo vital: el daño que reparte cura otro tanto a tu Nexo.',
    flavor: 'Conoce cada sendero porque los ha cerrado todos alguna vez.',
    keywords: ['lifelink'], collectorNumber: 102, aiTags: ['ranged', 'heal'], unique: false, effects: [],
    vfx: { summonEffect: 'leaf-step', attackEffect: 'thorn-shot' },
    set: SECOND_WAVE_SET,
  }),

  // --- Orden ---
  defineCard({
    id: 'arcangel-del-veredicto', name: 'Arcángel del Veredicto', faction: 'order', type: 'unit', subtype: 'Celestial',
    rarity: 'mythic', cost: factionCost('order', 2, 4), attack: 6, health: 6, range: 1, movement: 2,
    rules: 'Volador, Vínculo vital. Al entrar en juego, aturde a la unidad enemiga con más Ataque.',
    flavor: 'No dicta sentencia. La recuerda.',
    keywords: ['flying', 'lifelink'], collectorNumber: 103, aiTags: ['finisher', 'control'], unique: true,
    effects: [{ kind: 'stun' }],
    vfx: { summonEffect: 'holy-descent', attackEffect: 'verdict-strike', impactEffect: 'stun-daze' },
    set: SECOND_WAVE_SET,
  }),
  defineCard({
    id: 'muro-de-plegarias', name: 'Muro de Plegarias', faction: 'order', type: 'structure', subtype: 'Fortaleza',
    rarity: 'rare', cost: factionCost('order', 1, 2), resistance: 8,
    rules: 'Guardia. Al final de tu turno, la unidad aliada más herida gana un escudo de 2.',
    flavor: 'Cada piedra lleva grabado un nombre que todavía reza.',
    keywords: ['guard'], collectorNumber: 104, aiTags: ['structure', 'defense'], unique: false,
    effects: [{ kind: 'passive', id: 'upkeep-shield-ally', value: 2 }],
    vfx: { summonEffect: 'bastion-raise', persistentEffect: 'prayer-light' },
    set: SECOND_WAVE_SET,
  }),
  defineCard({
    id: 'sentencia-solar', name: 'Sentencia Solar', faction: 'order', type: 'instant', subtype: 'Conjuro',
    rarity: 'rare', cost: factionCost('order', 1, 2),
    rules: 'Inflige 3 de daño a todas las unidades enemigas. Cura 3 a tu Nexo.',
    flavor: 'El sol no juzga por bando, solo por sombra.',
    keywords: [], collectorNumber: 105, aiTags: ['area-damage', 'heal'], unique: false,
    effects: [{ kind: 'damage-all-enemies', amount: 3 }, { kind: 'heal-nexus', amount: 3 }],
    vfx: { impactEffect: 'solar-verdict' },
    set: SECOND_WAVE_SET,
  }),
  defineCard({
    id: 'escudera-del-alba', name: 'Escudera del Alba', faction: 'order', type: 'unit', subtype: 'Soldado',
    rarity: 'common', cost: factionCost('order', 1), attack: 1, health: 4, range: 1, movement: 1,
    rules: 'Guardia. Al entrar en juego, gana un escudo de 2.',
    flavor: 'Aún no tiene título. Ya tiene turno de guardia.',
    keywords: ['guard'], collectorNumber: 106, aiTags: ['defense', 'cheap'], unique: false,
    effects: [{ kind: 'passive', id: 'entry-shield-gain', value: 2 }],
    vfx: { summonEffect: 'dawn-shield', persistentEffect: 'shield-sheen' },
    set: SECOND_WAVE_SET,
  }),

  // --- Sombra ---
  defineCard({
    id: 'senora-de-la-mortaja', name: 'Señora de la Mortaja', faction: 'shadow', type: 'unit', subtype: 'Humanoide',
    rarity: 'mythic', cost: factionCost('shadow', 2, 3), attack: 5, health: 5, range: 1, movement: 2,
    rules: 'Vínculo vital. Al entrar en juego, el rival descarta 1 carta.',
    flavor: 'Teje la mortaja antes de saber quién la va a llevar.',
    keywords: ['lifelink'], collectorNumber: 107, aiTags: ['disruption', 'heal'], unique: true,
    effects: [{ kind: 'discard', amount: 1, target: 'enemy-hand' }],
    vfx: { summonEffect: 'shroud-weave', attackEffect: 'shadow-cut' },
    set: SECOND_WAVE_SET,
  }),
  defineCard({
    id: 'diezmo-de-sangre', name: 'Diezmo de Sangre', faction: 'shadow', type: 'instant', subtype: 'Ritual',
    rarity: 'uncommon', cost: factionCost('shadow', 1, 1),
    rules: 'El rival descarta 1 carta. Tu Nexo se cura 3.',
    flavor: 'El precio se cobra siempre. La discusión es de quién.',
    keywords: [], collectorNumber: 108, aiTags: ['disruption', 'heal'], unique: false,
    effects: [{ kind: 'discard', amount: 1, target: 'enemy-hand' }, { kind: 'heal-nexus', amount: 3 }],
    vfx: { impactEffect: 'blood-tithe' },
    set: SECOND_WAVE_SET,
  }),
  defineCard({
    id: 'carronero-del-osario', name: 'Carroñero del Osario', faction: 'shadow', type: 'unit', subtype: 'No muerto',
    rarity: 'common', cost: factionCost('shadow', 1), attack: 2, health: 2, range: 1, movement: 2,
    rules: 'Impulso. Cuando destruye una unidad, tu Nexo se cura 1.',
    flavor: 'Llega el último y se va el primero.',
    keywords: ['impulse'], collectorNumber: 109, aiTags: ['aggressive', 'heal'], unique: false,
    effects: [{ kind: 'passive', id: 'on-kill-heal-nexus', value: 1 }],
    vfx: { summonEffect: 'bone-stir', attackEffect: 'carrion-bite' },
    set: SECOND_WAVE_SET,
  }),
  defineCard({
    id: 'mausoleo-hambriento', name: 'Mausoleo Hambriento', faction: 'shadow', type: 'structure', subtype: 'Mausoleo',
    rarity: 'rare', cost: factionCost('shadow', 1, 2), resistance: 6,
    rules: 'Al final de tu turno, inflige 1 de daño al Nexo enemigo y cura 1 al tuyo.',
    flavor: 'Nunca está lleno. Ese es el problema de los mausoleos buenos.',
    keywords: [], collectorNumber: 110, aiTags: ['structure', 'drain'], unique: false,
    effects: [{ kind: 'passive', id: 'upkeep-drain-nexus', value: 1 }],
    vfx: { summonEffect: 'crypt-rise', persistentEffect: 'hungry-dark' },
    set: SECOND_WAVE_SET,
  }),

  // --- Vacío ---
  defineCard({
    id: 'arquitecta-del-vacio', name: 'Arquitecta del Vacío', faction: 'void', type: 'unit', subtype: 'Humanoide',
    rarity: 'mythic', cost: factionCost('void', 2, 3), attack: 4, health: 6, range: 2, movement: 2,
    rules: 'Golpe veloz. Al entrar en juego, una unidad aliada que ya se haya movido puede volver a moverse.',
    flavor: 'Dibuja la puerta y después la pared que la sostiene.',
    keywords: ['swift-strike'], collectorNumber: 111, aiTags: ['tempo', 'ranged'], unique: true,
    effects: [{ kind: 'refresh-move' }],
    vfx: { summonEffect: 'rift-open', attackEffect: 'void-lash', impactEffect: 'astral-refresh' },
    set: SECOND_WAVE_SET,
  }),
  defineCard({
    id: 'salto-de-umbral', name: 'Salto de Umbral', faction: 'void', type: 'instant', subtype: 'Portal',
    rarity: 'rare', cost: factionCost('void', 1, 1),
    rules: 'Una unidad aliada puede volver a moverse y gana Perforar hasta el final del turno.',
    flavor: 'El camino corto siempre existió. Solo hacía falta abrirlo.',
    keywords: [], collectorNumber: 112, aiTags: ['tempo', 'combat'], unique: false,
    effects: [{ kind: 'refresh-move' }, { kind: 'grant-keyword', keyword: 'pierce' }],
    vfx: { impactEffect: 'threshold-leap' },
    set: SECOND_WAVE_SET,
  }),
  defineCard({
    id: 'faro-de-la-fractura', name: 'Faro de la Fractura', faction: 'void', type: 'structure', subtype: 'Portal',
    rarity: 'rare', cost: factionCost('void', 1, 2), resistance: 5,
    rules: 'Al final de tu turno, robas 1 carta y descartas 1.',
    flavor: 'No señala la costa. Señala la grieta.',
    keywords: [], collectorNumber: 113, aiTags: ['structure', 'draw'], unique: false,
    effects: [{ kind: 'passive', id: 'upkeep-loot', value: 1 }],
    vfx: { summonEffect: 'beacon-ignite', persistentEffect: 'fracture-beam' },
    set: SECOND_WAVE_SET,
  }),
  defineCard({
    id: 'devorador-de-ecos', name: 'Devorador de Ecos', faction: 'void', type: 'unit', subtype: 'Horror',
    rarity: 'uncommon', cost: factionCost('void', 1, 1), attack: 3, health: 3, range: 1, movement: 2,
    rules: 'Cuando ataca, el rival descarta 1 carta.',
    flavor: 'Se alimenta de lo que ibas a decir.',
    keywords: [], collectorNumber: 114, aiTags: ['aggressive', 'disruption'], unique: false,
    effects: [{ kind: 'passive', id: 'attack-enemy-discard', value: 1 }],
    vfx: { summonEffect: 'echo-swallow', attackEffect: 'echo-bite' },
    set: SECOND_WAVE_SET,
  }),
];

export const CARDS = Object.freeze([
  ...furyCards, ...arcaneCards, ...natureCards, ...orderCards, ...shadowCards, ...voidCards,
  ...secondWaveCards,
]) as readonly CardDefinition[];

if (CARDS.length !== 114 || new Set(CARDS.map((card) => card.id)).size !== 114) {
  throw new Error('El catálogo debe contener 114 cartas (90 de NEX-01 y 24 de NEX-02) con identificadores únicos.');
}

export const CARD_BY_ID: Readonly<Record<string, CardDefinition>> = Object.freeze(
  Object.fromEntries(CARDS.map((card) => [card.id, card])),
);

export const cardsForFaction = (faction: FactionId): readonly CardDefinition[] =>
  CARDS.filter((card) => card.faction === faction);

export const MANDATORY_CARD_IDS = [
  'fuente-furia', 'sabueso-brasa', 'berserker-ignivoro', 'dragon-caldera', 'lluvia-ceniza', 'forja-carmesi',
  'fuente-arcana', 'centinela-cristal', 'tejedora-escarcha', 'prision-glacial', 'cometa-arcano', 'torre-horizonte',
] as const;
