import { FACTION_BY_ID } from './factions';
import { CardDefinitionSchema } from './schemas';
import type { CardDefinition, CardSfx, FactionId, ManaCost } from './types';

type CardSeed = Omit<
  CardDefinition,
  'color' | 'art' | 'set' | 'artist' | 'unlocked' | 'sfx'
> & { readonly sfx?: CardSfx };

const factionCost = (faction: FactionId, colored: number, generic = 0): ManaCost => ({
  generic,
  colored: colored === 0 ? {} : { [faction]: colored },
});

const ARTIST_CREDITS: Readonly<Record<string, string>> = Object.freeze({
  'fuente-furia': 'L. Valcazar, M. Iriarte & Taller de Luz Volcanica',
  'sabueso-brasa': 'V. Sanz, I. Rauk & Taller de Bestiario Igneo',
  'berserker-ignivoro': 'A. Montiel, C. Nervo & Taller de Oleo Heroico',
  'dragon-caldera': 'S. Aranda, D. Korr & Taller de Mural Epico',
  'lluvia-ceniza': 'N. Beltran, E. Ros & Taller de Atmosfera Negra',
  'forja-carmesi': 'P. Duarte, L. Maceira & Taller de Metal Ritual',
  'lancera-magma': 'R. Astar, M. Quiral & Taller de Figura Dinamica',
  'fenix-pavesa': 'C. Echevarri, A. Soler & Taller de Gouache Luminoso',
  'ariete-volcanico': 'B. Iriondo, T. Mallo & Taller de Perspectiva Baja',
  'pacto-ascuas': 'F. Lera, O. Vey & Taller de Ritual Intimo',
  'altar-combustion': 'H. Nadir, S. Coto & Taller Simbolista',
  'temblor-rojo': 'D. Salvat, J. Roca & Taller de Paisaje Cataclismico',
  'erupcion-volcanica': 'N. Beltran, E. Ros & Taller de Atmosfera Negra Expandida',
  'gigante-magma': 'L. Valcazar, J. Fuentes & Taller de Titan Igneo',
  'draco-magma': 'S. Aranda, D. Korr & Taller de Dragón Abismal',
  'infiltrado-volcanico': 'V. Sanz, T. Noir & Taller de Sombra Ardiente',
  'elemental-tormenta': 'N. Beltran, E. Ros & Taller de Clima Elemental',
  'fuente-arcana': 'M. Olarte, L. Vesper & Taller de Acuarela Luminica',
  'centinela-cristal': 'E. Rivas, N. Calve & Taller de Prisma Mineral',
  'tejedora-escarcha': 'I. Llorens, A. Vela & Taller de Figura Elegante',
  'prision-glacial': 'Q. Soria, L. Mael & Taller de Arquitectura Fria',
  'cometa-arcano': 'T. Nerea, B. Voss & Taller Astronomico',
  'torre-horizonte': 'G. Estel, M. Bruma & Taller de Arquitectura Romantica',
  'duelista-prisma': 'A. Faber, C. Lince & Taller de Esgrima Prismatica',
  'golem-azur': 'R. Navas, E. Aro & Taller de Criatura Mineral',
  'niebla-espejada': 'V. Merin, S. Albor & Taller de Nocturno Surreal',
  'eco-cronomante': 'J. Auren, P. Sibil & Taller Simbolista Arcano',
  'archivo-viviente': 'M. Doria, H. Clave & Taller de Biblioteca Imposible',
  'convergencia-astral': 'K. Morat, I. Serna & Taller de Geometria Cosmica',
  'congelacion-rapida': 'Q. Soria, L. Mael & Taller de Hielo Explosivo',
  'dragon-escarcha': 'E. Rivas, N. Calve & Taller de Dragón Glacial',
  'guardian-escarchado': 'R. Navas, E. Aro & Taller de Centinela Perenne',
  'destello-runico': 'T. Nerea, B. Voss & Taller de Magia Refulgente',
  'mago-celestial': 'M. Olarte, L. Vesper & Taller de Mago Estelar',
});

const defineCard = (seed: CardSeed): CardDefinition => {
  const definition: CardDefinition = {
    ...seed,
    color: FACTION_BY_ID[seed.faction].color,
    art: {
      webp: `/assets/cards/art/${seed.id}.webp`,
      fallback: `/assets/cards/art/${seed.id}.svg`,
      alt: `Ilustración de ${seed.name}`,
    },
    set: 'NEX-01 · Despertar',
    artist: ARTIST_CREDITS[seed.id] ?? 'Atelier del Nexo',
    unlocked: true,
    sfx: seed.sfx ?? { play: `${seed.faction}-play`, impact: `${seed.faction}-impact` },
  };
  return CardDefinitionSchema.parse(definition) as CardDefinition;
};

const furyCards: readonly CardDefinition[] = [
  defineCard({
    id: 'fuente-furia', name: 'Fuente de Furia', faction: 'fury', type: 'mana', subtype: 'Fuente',
    rarity: 'common', cost: factionCost('fury', 0),
    rules: 'Agota esta fuente: genera 1 de Esencia Carmesí.',
    flavor: 'Bajo la montaña, el corazón del mundo todavía arde.',
    keywords: [], collectorNumber: 1, aiTags: ['resource'], unique: false, effects: [],
    vfx: { persistentEffect: 'fury-source-embers' }, sfx: { play: 'resource-fury' },
  }),
  defineCard({
    id: 'sabueso-brasa', name: 'Sabueso de Brasa', faction: 'fury', type: 'unit', subtype: 'Bestia',
    rarity: 'common', cost: factionCost('fury', 1), attack: 2, health: 1, range: 1, movement: 2,
    rules: 'Impulso: puede moverse el turno en que entra en juego.',
    flavor: 'No persigue el olor de la sangre, sino el miedo que la precede.',
    keywords: ['impulse'], collectorNumber: 2, aiTags: ['aggressive', 'fast'], unique: false, effects: [],
    vfx: { summonEffect: 'ember-pounce', attackEffect: 'ember-trail', deathEffect: 'ash-burst' },
  }),
  defineCard({
    id: 'berserker-ignivoro', name: 'Berserker Ignívoro', faction: 'fury', type: 'unit', subtype: 'Guerrero',
    rarity: 'uncommon', cost: factionCost('fury', 2, 1), attack: 3, health: 3, range: 1, movement: 2,
    rules: 'Cuando ataque por primera vez cada turno, obtiene +1 Ataque durante ese combate.',
    flavor: 'Cada cicatriz es una puerta por la que vuelve a entrar el fuego.',
    keywords: [], collectorNumber: 3, aiTags: ['aggressive', 'combat'], unique: false,
    effects: [{ kind: 'buff-self-on-attack', attack: 1 }],
    vfx: { summonEffect: 'fury-cracks', attackEffect: 'rage-flare', impactEffect: 'heavy-impact' },
  }),
  defineCard({
    id: 'dragon-caldera', name: 'Dragón de la Caldera', faction: 'fury', type: 'unit', subtype: 'Dragón',
    rarity: 'mythic', cost: factionCost('fury', 2, 5), attack: 7, health: 6, range: 1, movement: 2,
    rules: 'Al entrar en juego, inflige 2 de daño a todas las demás cartas de las casillas adyacentes.',
    flavor: 'La Caldera no entró en erupción. Simplemente abrió los ojos.',
    keywords: [], collectorNumber: 4, aiTags: ['finisher', 'area-damage'], unique: true,
    effects: [{ kind: 'adjacent-damage', amount: 2, includeAllies: true }],
    vfx: { summonEffect: 'caldera-eruption', attackEffect: 'dragon-flame', deathEffect: 'volcanic-collapse' },
  }),
  defineCard({
    id: 'lluvia-ceniza', name: 'Lluvia de Ceniza', faction: 'fury', type: 'instant', subtype: 'Conjuro',
    rarity: 'uncommon', cost: factionCost('fury', 1, 2),
    rules: 'Inflige 2 de daño a una unidad. Su casilla queda abrasada hasta el final del siguiente turno.',
    flavor: 'Cuando el cielo se vuelve gris, hasta las sombras buscan refugio.',
    keywords: [], collectorNumber: 5, aiTags: ['removal', 'damage'], unique: false,
    effects: [{ kind: 'damage', amount: 2, target: 'enemy-piece' }, { kind: 'scorch', duration: 1 }],
    vfx: { impactEffect: 'ash-rain', persistentEffect: 'scorched-tile' }, sfx: { play: 'ash-rain', impact: 'fire-impact' },
  }),
  defineCard({
    id: 'forja-carmesi', name: 'Forja Carmesí', faction: 'fury', type: 'structure', subtype: 'Forja',
    rarity: 'rare', cost: factionCost('fury', 1, 2), resistance: 5,
    rules: 'La primera unidad de Furia que juegues cada turno obtiene +1 Ataque hasta el final del turno.',
    flavor: 'Aquí no se fabrican armas. Se despierta su hambre.',
    keywords: [], collectorNumber: 6, aiTags: ['structure', 'buff'], unique: false,
    effects: [{ kind: 'passive', id: 'first-fury-unit-attack', value: 1 }],
    vfx: { summonEffect: 'forge-rise', persistentEffect: 'forge-glow', deathEffect: 'forge-collapse' },
  }),
  defineCard({
    id: 'lancera-magma', name: 'Lancera de Magma', faction: 'fury', type: 'unit', subtype: 'Guerrera',
    rarity: 'common', cost: factionCost('fury', 1, 1), attack: 2, health: 2, range: 1, movement: 2,
    rules: 'Impulso. Puede avanzar hasta 2 casillas si ambas están libres.',
    flavor: 'La lava siempre encuentra una grieta; su lanza también.',
    keywords: ['impulse'], collectorNumber: 7, aiTags: ['fast', 'flanker'], unique: false, effects: [],
    vfx: { summonEffect: 'slag-sparks', attackEffect: 'cinder-dash' },
  }),
  defineCard({
    id: 'fenix-pavesa', name: 'Fénix de Pavesa', faction: 'fury', type: 'unit', subtype: 'Ave ígnea',
    rarity: 'uncommon', cost: factionCost('fury', 1, 2), attack: 2, health: 3, range: 2, movement: 2,
    rules: 'Al entrar en juego, inflige 1 de daño a una carta enemiga adyacente.',
    flavor: 'Cada una de sus plumas recuerda un incendio distinto.',
    keywords: [], collectorNumber: 8, aiTags: ['ranged', 'damage'], unique: false,
    effects: [{ kind: 'passive', id: 'entry-adjacent-enemy-damage', value: 1 }],
    vfx: { summonEffect: 'rift-open', attackEffect: 'fire-bolt', impactEffect: 'magma-pop' },
  }),
  defineCard({
    id: 'ariete-volcanico', name: 'Ariete Volcánico', faction: 'fury', type: 'unit', subtype: 'Constructo',
    rarity: 'rare', cost: factionCost('fury', 2, 2), attack: 4, health: 5, range: 1, movement: 1,
    rules: 'Cuando daña una estructura, inflige 2 de daño adicional.',
    flavor: 'La puerta cede mucho antes que la piedra se canse.',
    keywords: [], collectorNumber: 9, aiTags: ['siege', 'durable'], unique: false,
    effects: [{ kind: 'passive', id: 'structure-bonus-damage', value: 2 }],
    vfx: { summonEffect: 'basalt-drop', attackEffect: 'siege-charge', impactEffect: 'stone-shockwave' },
  }),
  defineCard({
    id: 'pacto-ascuas', name: 'Pacto de Ascuas', faction: 'fury', type: 'instant', subtype: 'Ritual',
    rarity: 'rare', cost: factionCost('fury', 1, 1),
    rules: 'Una unidad aliada obtiene +2 Ataque hasta el final del turno.',
    flavor: 'Un juramento pronunciado sobre carbón nunca se enfría.',
    keywords: [], collectorNumber: 10, aiTags: ['buff', 'combat'], unique: false,
    effects: [{ kind: 'passive', id: 'target-attack-until-end', value: 2 }],
    vfx: { impactEffect: 'ember-oath' },
  }),
  defineCard({
    id: 'altar-combustion', name: 'Altar de Combustión', faction: 'fury', type: 'structure', subtype: 'Altar',
    rarity: 'common', cost: factionCost('fury', 1, 1), resistance: 4,
    rules: 'Las unidades enemigas no pueden atravesar esta casilla.',
    flavor: 'La llama acepta todas las ofrendas y nunca concede absolución.',
    keywords: ['guard'], collectorNumber: 11, aiTags: ['structure', 'defense'], unique: false,
    effects: [{ kind: 'passive', id: 'blocking-structure' }],
    vfx: { summonEffect: 'magma-wall', persistentEffect: 'heat-haze' },
  }),
  defineCard({
    id: 'temblor-rojo', name: 'Temblor Rojo', faction: 'fury', type: 'persistent', subtype: 'Cataclismo',
    rarity: 'rare', cost: factionCost('fury', 2, 2),
    rules: 'Inflige 3 de daño a una unidad. Después, la réplica inflige 1 de daño a la unidad enemiga más debilitada restante.',
    flavor: 'La tierra aprende a rugir antes de abrirse.',
    keywords: [], collectorNumber: 12, aiTags: ['removal', 'damage'], unique: false,
    effects: [{ kind: 'damage', amount: 3, target: 'enemy-piece' }, { kind: 'splash-weakest-enemy', amount: 1 }],
    vfx: { impactEffect: 'chain-eruption', persistentEffect: 'magma-chain' },
  }),
  defineCard({
    id: 'erupcion-volcanica', name: 'Erupción Volcánica', faction: 'fury', type: 'instant', subtype: 'Catástrofe',
    rarity: 'uncommon', cost: factionCost('fury', 1, 2),
    rules: 'Inflige 2 de daño a cada unidad enemiga. Las casillas afectadas permanecen abrasadas.',
    flavor: 'El cielo se parte cuando la tierra elige hablar.',
    keywords: [], collectorNumber: 25, aiTags: ['removal', 'area-damage'], unique: false,
    effects: [{ kind: 'damage', amount: 2, target: 'enemy-piece' }, { kind: 'scorch', duration: 1 }],
    vfx: { impactEffect: 'volcanic-burst', persistentEffect: 'lava-shockwave' },
  }),
  defineCard({
    id: 'gigante-magma', name: 'Gigante de Magma', faction: 'fury', type: 'unit', subtype: 'Gigante',
    rarity: 'rare', cost: factionCost('fury', 3, 2), attack: 5, health: 6, range: 1, movement: 1,
    rules: 'Las casillas adyacentes permanecen abrasadas.',
    flavor: 'Cada paso deja un valle de fuego donde antes había tierra fértil.',
    keywords: [], collectorNumber: 26, aiTags: ['durable', 'area-control'], unique: false,
    effects: [{ kind: 'passive', id: 'scorch-adjacents' }],
    vfx: { summonEffect: 'magma-rise', persistentEffect: 'heat-aura' },
  }),
  defineCard({
    id: 'draco-magma', name: 'Draco de Magma', faction: 'fury', type: 'unit', subtype: 'Dragón',
    rarity: 'mythic', cost: factionCost('fury', 2, 4), attack: 6, health: 5, range: 2, movement: 2,
    rules: 'Impulso. Cuando ataca, las casillas adyacentes al objetivo reciben daño de fuego.',
    flavor: 'Su aliento convierte arena en cristal, en un instante.',
    keywords: ['impulse'], collectorNumber: 27, aiTags: ['finisher', 'ranged'], unique: false,
    effects: [{ kind: 'adjacent-damage', amount: 1, includeAllies: false }],
    vfx: { summonEffect: 'dragon-awaken', attackEffect: 'magma-beam', deathEffect: 'dragon-collapse' },
  }),
  defineCard({
    id: 'infiltrado-volcanico', name: 'Infiltrado Volcánico', faction: 'fury', type: 'unit', subtype: 'Bandido',
    rarity: 'common', cost: factionCost('fury', 1), attack: 2, health: 2, range: 1, movement: 2,
    rules: 'Impulso: puede moverse el turno en que entra en juego. +1 Ataque contra unidades solitarias.',
    flavor: 'Aparece donde nadie lo espera y desaparece en el humo.',
    keywords: ['impulse'], collectorNumber: 28, aiTags: ['aggressive', 'assassin'], unique: false,
    effects: [{ kind: 'passive', id: 'bonus-damage-isolated-target', value: 1 }],
    vfx: { summonEffect: 'smoke-rise', attackEffect: 'cinder-strike' },
  }),
  defineCard({
    id: 'elemental-tormenta', name: 'Elemental de Tormenta', faction: 'fury', type: 'unit', subtype: 'Elemental',
    rarity: 'uncommon', cost: factionCost('fury', 1, 2), attack: 2, health: 4, range: 2, movement: 2,
    rules: 'Rango 2. Cuando ataca, inflige 1 de daño adicional a la unidad objetivo.',
    flavor: 'Nubes ardientes que gritan en lengua de trueno y ceniza.',
    keywords: [], collectorNumber: 34, aiTags: ['ranged', 'damage'], unique: false,
    effects: [{ kind: 'damage', amount: 1, target: 'enemy-piece' }],
    vfx: { summonEffect: 'storm-gather', attackEffect: 'lightning-strike', impactEffect: 'thunder-boom' },
  }),
];

const arcaneCards: readonly CardDefinition[] = [
  defineCard({
    id: 'fuente-arcana', name: 'Fuente Arcana', faction: 'arcane', type: 'mana', subtype: 'Fuente',
    rarity: 'common', cost: factionCost('arcane', 0),
    rules: 'Agota esta fuente: genera 1 de Esencia Celeste.',
    flavor: 'Cada cristal conserva una pregunta que el mundo aún no sabe responder.',
    keywords: [], collectorNumber: 13, aiTags: ['resource'], unique: false, effects: [],
    vfx: { persistentEffect: 'arcane-source-runes' }, sfx: { play: 'resource-arcane' },
  }),
  defineCard({
    id: 'centinela-cristal', name: 'Centinela de Cristal', faction: 'arcane', type: 'unit', subtype: 'Constructo',
    rarity: 'common', cost: factionCost('arcane', 1, 1), attack: 1, health: 3, range: 1, movement: 1,
    rules: 'Al entrar en juego, observa las dos primeras cartas de tu mazo y colócalas en el orden que quieras.',
    flavor: 'No piensa, no duerme y jamás olvida una orden.',
    keywords: [], collectorNumber: 14, aiTags: ['defense', 'scry'], unique: false,
    effects: [{ kind: 'scry', amount: 2 }],
    vfx: { summonEffect: 'crystal-assemble', attackEffect: 'crystal-swipe', deathEffect: 'crystal-shatter' },
  }),
  defineCard({
    id: 'tejedora-escarcha', name: 'Tejedora de Escarcha', faction: 'arcane', type: 'unit', subtype: 'Hechicera',
    rarity: 'uncommon', cost: factionCost('arcane', 2, 1), attack: 2, health: 3, range: 2, movement: 2,
    rules: 'Cuando dañe a una unidad, esa unidad no podrá moverse durante su próximo turno.',
    flavor: 'Con un gesto detiene el agua. Con una palabra, detiene ejércitos.',
    keywords: [], collectorNumber: 15, aiTags: ['ranged', 'control'], unique: false,
    effects: [{ kind: 'passive', id: 'freeze-on-damage', value: 1 }],
    vfx: { summonEffect: 'frost-weave', attackEffect: 'ice-thread', impactEffect: 'freeze-lock' },
  }),
  defineCard({
    id: 'prision-glacial', name: 'Prisión Glacial', faction: 'arcane', type: 'persistent', subtype: 'Encantamiento',
    rarity: 'uncommon', cost: factionCost('arcane', 1, 1),
    rules: 'Congela una unidad hasta el comienzo de tu siguiente turno. No puede moverse ni atacar.',
    flavor: 'El hielo no encierra el cuerpo. Convence al tiempo de que deje de avanzar.',
    keywords: [], collectorNumber: 16, aiTags: ['freeze', 'control'], unique: false,
    effects: [{ kind: 'freeze', duration: 1 }],
    vfx: { impactEffect: 'glacial-prison', persistentEffect: 'frozen-runes' },
  }),
  defineCard({
    id: 'cometa-arcano', name: 'Cometa Arcano', faction: 'arcane', type: 'instant', subtype: 'Evocación',
    rarity: 'rare', cost: factionCost('arcane', 2, 3),
    rules: 'Inflige 4 de daño a una unidad o estructura. Si el objetivo estaba congelado, inflige 2 de daño adicional.',
    flavor: 'Los sabios estudian las estrellas. Los necios esperan a que caigan.',
    keywords: [], collectorNumber: 17, aiTags: ['removal', 'damage'], unique: false,
    effects: [{ kind: 'damage', amount: 4, target: 'any-piece' }, { kind: 'passive', id: 'frozen-bonus-damage', value: 2 }],
    vfx: { impactEffect: 'arcane-comet' }, sfx: { play: 'comet-cast', impact: 'comet-impact' },
  }),
  defineCard({
    id: 'torre-horizonte', name: 'Torre del Horizonte', faction: 'arcane', type: 'structure', subtype: 'Observatorio',
    rarity: 'rare', cost: factionCost('arcane', 1, 3), resistance: 5,
    rules: 'Una vez por turno, después de lanzar un hechizo, puedes robar una carta y descartar otra.',
    flavor: 'Desde lo alto puede verse el futuro, pero nunca el precio de alcanzarlo.',
    keywords: [], collectorNumber: 18, aiTags: ['structure', 'draw'], unique: false,
    effects: [{ kind: 'passive', id: 'loot-after-spell', value: 1 }],
    vfx: { summonEffect: 'tower-rise', persistentEffect: 'horizon-orbit', deathEffect: 'rune-collapse' },
  }),
  defineCard({
    id: 'duelista-prisma', name: 'Duelista del Prisma', faction: 'arcane', type: 'unit', subtype: 'Místico',
    rarity: 'common', cost: factionCost('arcane', 1), attack: 1, health: 2, range: 1, movement: 2,
    rules: 'Al entrar en juego, roba una carta y luego descarta una carta.',
    flavor: 'Su hoja elige un color distinto para cada adversario.',
    keywords: [], collectorNumber: 19, aiTags: ['draw', 'utility'], unique: false,
    effects: [{ kind: 'draw', amount: 1 }, { kind: 'discard', amount: 1 }],
    vfx: { summonEffect: 'seven-runes', attackEffect: 'rune-pulse' },
  }),
  defineCard({
    id: 'golem-azur', name: 'Gólem Azur', faction: 'arcane', type: 'unit', subtype: 'Constructo',
    rarity: 'uncommon', cost: factionCost('arcane', 1, 2), attack: 2, health: 5, range: 1, movement: 1,
    rules: 'La primera vez que reciba daño cada turno, reduce ese daño en 1.',
    flavor: 'Su núcleo contiene un mar que jamás conoció orillas.',
    keywords: ['guard'], collectorNumber: 20, aiTags: ['defense', 'durable'], unique: false,
    effects: [{ kind: 'passive', id: 'first-damage-reduction', value: 1 }],
    vfx: { summonEffect: 'azur-assemble', impactEffect: 'water-shield', deathEffect: 'azur-shatter' },
  }),
  defineCard({
    id: 'niebla-espejada', name: 'Niebla Espejada', faction: 'arcane', type: 'persistent', subtype: 'Encantamiento',
    rarity: 'rare', cost: factionCost('arcane', 2, 1),
    rules: 'Observa las tres primeras cartas de tu mazo y colócalas en el orden que quieras. Después, roba una carta.',
    flavor: 'Cada reflejo oculta a quien lo está mirando.',
    keywords: [], collectorNumber: 21, aiTags: ['scry', 'draw'], unique: false,
    effects: [{ kind: 'scry', amount: 3 }, { kind: 'draw', amount: 1 }],
    vfx: { summonEffect: 'mirror-unfold', persistentEffect: 'probability-shimmer' },
  }),
  defineCard({
    id: 'eco-cronomante', name: 'Eco Cronomante', faction: 'arcane', type: 'instant', subtype: 'Cronomancia',
    rarity: 'common', cost: factionCost('arcane', 1, 1),
    rules: 'Roba 2 cartas y luego descarta una carta.',
    flavor: 'Su voz llega siempre un instante antes que sus labios.',
    keywords: [], collectorNumber: 22, aiTags: ['draw', 'selection'], unique: false,
    effects: [{ kind: 'draw', amount: 2 }, { kind: 'discard', amount: 1 }],
    vfx: { impactEffect: 'time-current' },
  }),
  defineCard({
    id: 'archivo-viviente', name: 'Archivo Viviente', faction: 'arcane', type: 'unit', subtype: 'Místico',
    rarity: 'mythic', cost: factionCost('arcane', 2, 4), attack: 4, health: 6, range: 2, movement: 1,
    rules: 'Al entrar en juego, roba 2 cartas. Tus hechizos cuestan 1 genérico menos, hasta un mínimo de 0.',
    flavor: 'Ha catalogado cada final salvo el suyo.',
    keywords: ['channel'], collectorNumber: 23, aiTags: ['finisher', 'draw'], unique: true,
    effects: [{ kind: 'draw', amount: 2 }, { kind: 'passive', id: 'spell-generic-discount', value: 1 }],
    vfx: { summonEffect: 'infinite-library', attackEffect: 'glyph-beam', deathEffect: 'pages-to-stars' },
  }),
  defineCard({
    id: 'convergencia-astral', name: 'Convergencia Astral', faction: 'arcane', type: 'persistent', subtype: 'Portal',
    rarity: 'uncommon', cost: factionCost('arcane', 1, 2),
    rules: 'Una unidad aliada puede moverse de nuevo este turno, aunque acabe de entrar en juego.',
    flavor: 'Cuando las estrellas coinciden, la distancia pierde toda autoridad.',
    keywords: [], collectorNumber: 24, aiTags: ['movement', 'control'], unique: false,
    effects: [{ kind: 'refresh-move' }],
    vfx: { impactEffect: 'folded-threshold', persistentEffect: 'portal-ripple' },
  }),
  defineCard({
    id: 'congelacion-rapida', name: 'Congelación Rápida', faction: 'arcane', type: 'instant', subtype: 'Encantamiento',
    rarity: 'common', cost: factionCost('arcane', 1, 1),
    rules: 'Congela una unidad enemiga durante 1 turno. No puede moverse ni atacar.',
    flavor: 'El tiempo se quiebra bajo el hielo.',
    keywords: [], collectorNumber: 29, aiTags: ['freeze', 'control'], unique: false,
    effects: [{ kind: 'freeze', duration: 1 }],
    vfx: { impactEffect: 'instant-freeze', persistentEffect: 'ice-shards' },
  }),
  defineCard({
    id: 'dragon-escarcha', name: 'Dragón de Escarcha', faction: 'arcane', type: 'unit', subtype: 'Dragón',
    rarity: 'mythic', cost: factionCost('arcane', 2, 4), attack: 5, health: 7, range: 2, movement: 2,
    rules: 'Cuando ataca, congela el objetivo durante el siguiente turno. Las unidades congeladas no pueden atacar.',
    flavor: 'Su cola barre el horizonte dejando nieve donde antes ardía.',
    keywords: [], collectorNumber: 30, aiTags: ['finisher', 'control'], unique: false,
    effects: [{ kind: 'freeze', duration: 1 }],
    vfx: { summonEffect: 'frost-awaken', attackEffect: 'ice-beam', deathEffect: 'snowstorm' },
  }),
  defineCard({
    id: 'guardian-escarchado', name: 'Guardián Escarchado', faction: 'arcane', type: 'unit', subtype: 'Constructo',
    rarity: 'uncommon', cost: factionCost('arcane', 1, 2), attack: 1, health: 5, range: 1, movement: 1, resistance: 3,
    rules: 'Las unidades enemigas adyacentes no pueden atacar.',
    flavor: 'Ni se mueve ni cede. Simplemente espera a que todo se paralice.',
    keywords: ['guard'], collectorNumber: 31, aiTags: ['defense', 'freeze'], unique: false,
    effects: [{ kind: 'passive', id: 'pacify-adjacent-enemies' }],
    vfx: { summonEffect: 'ice-wall', persistentEffect: 'permafrost-aura' },
  }),
  defineCard({
    id: 'destello-runico', name: 'Destello Rúnico', faction: 'arcane', type: 'instant', subtype: 'Hechizo',
    rarity: 'uncommon', cost: factionCost('arcane', 1, 1),
    rules: 'Inflige 2 de daño a una unidad enemiga. Roba una carta.',
    flavor: 'Cada runa que desata revela un secreto del universo.',
    keywords: [], collectorNumber: 32, aiTags: ['damage', 'draw'], unique: false,
    effects: [{ kind: 'damage', amount: 2, target: 'enemy-piece' }, { kind: 'draw', amount: 1 }],
    vfx: { impactEffect: 'rune-flash', persistentEffect: 'knowledge-surge' },
  }),
  defineCard({
    id: 'mago-celestial', name: 'Mago Celestial', faction: 'arcane', type: 'unit', subtype: 'Mago',
    rarity: 'rare', cost: factionCost('arcane', 1, 3), attack: 3, health: 3, range: 3, movement: 1,
    rules: 'Rango 3. Gana +1 Ataque cuando ataca desde casillas no adyacentes.',
    flavor: 'Ve más allá de las nubes, donde habita el lenguaje de los dioses.',
    keywords: [], collectorNumber: 33, aiTags: ['ranged', 'spell-synergy'], unique: false,
    effects: [{ kind: 'passive', id: 'ranged-attack-bonus', value: 1 }],
    vfx: { summonEffect: 'celestial-descent', attackEffect: 'starlight-bolt', persistentEffect: 'cosmic-aura' },
  }),
];

const natureCards: readonly CardDefinition[] = [
  defineCard({
    id: 'fuente-naturaleza', name: 'Fuente Naturaleza', faction: 'nature', type: 'mana', subtype: 'Fuente',
    rarity: 'common', cost: factionCost('nature', 0),
    rules: 'Agota esta fuente: genera 1 de Esencia Verdadera.',
    flavor: 'La tierra respira en ciclos sin fin.',
    keywords: [], collectorNumber: 35, aiTags: ['resource'], unique: false, effects: [],
    vfx: { persistentEffect: 'nature-source-growth' }, sfx: { play: 'resource-nature' },
  }),
  defineCard({
    id: 'ciervo-sagrado', name: 'Ciervo Sagrado', faction: 'nature', type: 'unit', subtype: 'Bestia',
    rarity: 'common', cost: factionCost('nature', 1), attack: 2, health: 2, range: 1, movement: 1,
    rules: 'Al entrar en juego, roba una carta.',
    flavor: 'Sus astas atrapan la luz del bosque.',
    keywords: [], collectorNumber: 36, aiTags: ['draw', 'utility'], unique: false, effects: [{ kind: 'draw', amount: 1 }],
    vfx: { summonEffect: 'antler-glow', attackEffect: 'leaf-strike' },
  }),
  defineCard({
    id: 'lobo-salvaje', name: 'Lobo Salvaje', faction: 'nature', type: 'unit', subtype: 'Bestia',
    rarity: 'common', cost: factionCost('nature', 1), attack: 2, health: 2, range: 1, movement: 2,
    rules: 'Impulso: puede moverse el turno en que entra en juego.',
    flavor: 'Caza en manadas donde nadie osa entrar.',
    keywords: ['impulse'], collectorNumber: 37, aiTags: ['aggressive', 'fast'], unique: false, effects: [],
    vfx: { summonEffect: 'howl-echo', attackEffect: 'pounce-strike' },
  }),
  defineCard({
    id: 'oso-forestal', name: 'Oso Forestal', faction: 'nature', type: 'unit', subtype: 'Bestia',
    rarity: 'uncommon', cost: factionCost('nature', 2, 1), attack: 4, health: 4, range: 1, movement: 1, resistance: 2,
    rules: 'Las demás unidades aliadas ganan +1 Vida.',
    flavor: 'Guardián del bosque profundo, inmemorial.',
    keywords: ['guard'], collectorNumber: 38, aiTags: ['durable', 'buff'], unique: false,
    effects: [{ kind: 'passive', id: 'buff-allied-units-health', value: 1 }],
    vfx: { summonEffect: 'bear-roar', persistentEffect: 'forest-aura' },
  }),
  defineCard({
    id: 'arboleda-sagrada', name: 'Arboleda Sagrada', faction: 'nature', type: 'structure', subtype: 'Arboleda',
    rarity: 'rare', cost: factionCost('nature', 2, 1), resistance: 5,
    rules: 'Las unidades aliadas al entrar en juego ganan +1 Vida.',
    flavor: 'Tierra virgen donde todo florece con propósito.',
    keywords: [], collectorNumber: 39, aiTags: ['structure', 'buff'], unique: false,
    effects: [{ kind: 'passive', id: 'entry-allied-units-gain-health', value: 1 }],
    vfx: { summonEffect: 'forest-bloom', persistentEffect: 'growth-aura' },
  }),
  defineCard({
    id: 'crecimiento-salvaje', name: 'Crecimiento Salvaje', faction: 'nature', type: 'instant', subtype: 'Conjuro',
    rarity: 'uncommon', cost: factionCost('nature', 1, 2),
    rules: 'Una unidad aliada gana +2 Vida y +1 Ataque hasta fin de turno.',
    flavor: 'La naturaleza siempre encuentra la forma de crecer.',
    keywords: [], collectorNumber: 40, aiTags: ['buff', 'combat'], unique: false,
    effects: [{ kind: 'passive', id: 'unit-buff-health-attack', value: 1 }],
    vfx: { impactEffect: 'vine-growth' },
  }),
  defineCard({
    id: 'centauro-cazador', name: 'Centauro Cazador', faction: 'nature', type: 'unit', subtype: 'Humanoid',
    rarity: 'uncommon', cost: factionCost('nature', 1, 2), attack: 3, health: 2, range: 2, movement: 2,
    rules: 'Cuando ataca, todas las unidades aliadas adyacentes ganan +1 Ataque.',
    flavor: 'Corredor veloz de los prados dorados.',
    keywords: [], collectorNumber: 41, aiTags: ['ranged', 'buff'], unique: false,
    effects: [{ kind: 'passive', id: 'attack-buff-nearby-allies', value: 1 }],
    vfx: { summonEffect: 'hooves-thunder', attackEffect: 'swift-charge' },
  }),
  defineCard({
    id: 'elfo-ancestral', name: 'Elfo Ancestral', faction: 'nature', type: 'unit', subtype: 'Humanoid',
    rarity: 'rare', cost: factionCost('nature', 2, 3), attack: 4, health: 3, range: 2, movement: 2,
    rules: 'Roba una carta cuando entra en juego. Tus instantes cuestan 1 genérico menos.',
    flavor: 'Antigua memoria viviente del primer bosque.',
    keywords: [], collectorNumber: 42, aiTags: ['finisher', 'draw'], unique: false,
    effects: [{ kind: 'draw', amount: 1 }, { kind: 'passive', id: 'instant-cost-discount', value: 1 }],
    vfx: { summonEffect: 'ancient-whisper', persistentEffect: 'elder-wisdom' },
  }),
];

const orderCards: readonly CardDefinition[] = [
  defineCard({
    id: 'fuente-orden', name: 'Fuente Orden', faction: 'order', type: 'mana', subtype: 'Fuente',
    rarity: 'common', cost: factionCost('order', 0),
    rules: 'Agota esta fuente: genera 1 de Esencia Soberana.',
    flavor: 'La ley perfecta grabada en cristal.',
    keywords: [], collectorNumber: 43, aiTags: ['resource'], unique: false, effects: [],
    vfx: { persistentEffect: 'order-source-light' }, sfx: { play: 'resource-order' },
  }),
  defineCard({
    id: 'angel-celestial', name: 'Ángel Celestial', faction: 'order', type: 'unit', subtype: 'Celestial',
    rarity: 'uncommon', cost: factionCost('order', 2, 1), attack: 3, health: 2, range: 2, movement: 1,
    rules: 'Cuando entra en juego, gana escudo preventivo 1.',
    flavor: 'Mensajero de la justicia eternal.',
    keywords: [], collectorNumber: 44, aiTags: ['defense', 'ranged'], unique: false,
    effects: [{ kind: 'passive', id: 'entry-shield-gain', value: 1 }],
    vfx: { summonEffect: 'heavenly-descent', persistentEffect: 'holy-light' },
  }),
  defineCard({
    id: 'aguila-celestial', name: 'Águila Celestial', faction: 'order', type: 'unit', subtype: 'Ave',
    rarity: 'common', cost: factionCost('order', 1, 2), attack: 2, health: 2, range: 2, movement: 2,
    rules: 'Vuelo. Puede atacar sin ser tocada por unidades terrestres.',
    flavor: 'Sus ojos vigilan desde las alturas.',
    keywords: ['flying'], collectorNumber: 45, aiTags: ['ranged', 'evasion'], unique: false, effects: [],
    vfx: { summonEffect: 'eagle-cry', attackEffect: 'dive-strike' },
  }),
  defineCard({
    id: 'pegaso-celestial', name: 'Pégaso Celestial', faction: 'order', type: 'unit', subtype: 'Bestia',
    rarity: 'rare', cost: factionCost('order', 2, 2), attack: 3, health: 3, range: 2, movement: 2,
    rules: 'Vuelo e impulso. Al atacar por primera vez, regenera 2 Vida.',
    flavor: 'Símbolo de libertad y nobleza sin fin.',
    keywords: ['flying', 'impulse'], collectorNumber: 46, aiTags: ['ranged', 'durable'], unique: false,
    effects: [{ kind: 'passive', id: 'first-attack-heal', value: 2 }],
    vfx: { summonEffect: 'winged-gallop', attackEffect: 'aerial-strike' },
  }),
  defineCard({
    id: 'paladin-glorioso', name: 'Paladín Glorioso', faction: 'order', type: 'unit', subtype: 'Humanoid',
    rarity: 'rare', cost: factionCost('order', 2, 3), attack: 4, health: 3, range: 1, movement: 1, resistance: 3,
    rules: 'Las unidades aliadas adyacentes no pueden ser congeladas.',
    flavor: 'Campeón de la fe que nunca retrocede.',
    keywords: ['guard'], collectorNumber: 47, aiTags: ['defense', 'protection'], unique: false,
    effects: [{ kind: 'passive', id: 'protect-adjacent-from-freeze' }],
    vfx: { summonEffect: 'divine-oath', persistentEffect: 'holy-protection' },
  }),
  defineCard({
    id: 'clerigo-luz', name: 'Clérigo de Luz', faction: 'order', type: 'unit', subtype: 'Humanoid',
    rarity: 'uncommon', cost: factionCost('order', 1, 1), attack: 1, health: 3, range: 2, movement: 1,
    rules: 'Cuando una unidad aliada es sanada, gana +1 Vida ese turno.',
    flavor: 'Su presencia sana las heridas más profundas.',
    keywords: [], collectorNumber: 48, aiTags: ['healer', 'support'], unique: false,
    effects: [{ kind: 'passive', id: 'heal-support-buff', value: 1 }],
    vfx: { summonEffect: 'healing-light', persistentEffect: 'blessed-aura' },
  }),
  defineCard({
    id: 'grifo-orden', name: 'Grifo de Orden', faction: 'order', type: 'unit', subtype: 'Bestia',
    rarity: 'uncommon', cost: factionCost('order', 2, 2), attack: 3, health: 3, range: 2, movement: 2,
    rules: 'Vigilancia. Las unidades enemigas adyacentes tienen -1 Ataque.',
    flavor: 'Guardián que previene todo caos y desorden.',
    keywords: ['guard'], collectorNumber: 49, aiTags: ['defense', 'control'], unique: false,
    effects: [{ kind: 'passive', id: 'weaken-adjacent-enemies', value: 1 }],
    vfx: { summonEffect: 'guardian-roar', persistentEffect: 'ward-aura' },
  }),
  defineCard({
    id: 'juicio-divino', name: 'Juicio Divino', faction: 'order', type: 'instant', subtype: 'Conjuro',
    rarity: 'rare', cost: factionCost('order', 1, 3),
    rules: 'Destruye una unidad enemiga con 2 Vida o menos. Gana 2 Vida.',
    flavor: 'La verdad juzga a todos sin piedad.',
    keywords: [], collectorNumber: 50, aiTags: ['removal', 'healing'], unique: false,
    effects: [{ kind: 'damage', amount: 99, target: 'enemy-piece' }, { kind: 'heal-nexus', amount: 2 }],
    vfx: { impactEffect: 'divine-judgment' },
  }),
];

const shadowCards: readonly CardDefinition[] = [
  defineCard({
    id: 'fuente-sombra', name: 'Fuente Sombra', faction: 'shadow', type: 'mana', subtype: 'Fuente',
    rarity: 'common', cost: factionCost('shadow', 0),
    rules: 'Agota esta fuente: genera 1 de Esencia Oscura.',
    flavor: 'Poder extraído de la eternidad silenciosa.',
    keywords: [], collectorNumber: 51, aiTags: ['resource'], unique: false, effects: [],
    vfx: { persistentEffect: 'shadow-source-drain' }, sfx: { play: 'resource-shadow' },
  }),
  defineCard({
    id: 'murcielago-sombra', name: 'Murciélago Sombra', faction: 'shadow', type: 'unit', subtype: 'Bestia',
    rarity: 'common', cost: factionCost('shadow', 1, 1), attack: 1, health: 2, range: 1, movement: 2,
    rules: 'Vuelo. Cuando ataca, drena 1 Vida al enemigo para ti.',
    flavor: 'Drenador silencioso de la noche profunda.',
    keywords: ['flying'], collectorNumber: 52, aiTags: ['lifedrain', 'evasion'], unique: false,
    effects: [{ kind: 'passive', id: 'drain-life-on-attack', value: 1 }],
    vfx: { summonEffect: 'shadow-wings', attackEffect: 'life-drain' },
  }),
  defineCard({
    id: 'espectro-siniestro', name: 'Espectro Siniestro', faction: 'shadow', type: 'unit', subtype: 'Espíritu',
    rarity: 'uncommon', cost: factionCost('shadow', 1, 2), attack: 2, health: 2, range: 1, movement: 2,
    rules: 'Incorporal. No puede ser bloqueado. Cuando daña, descarta una carta enemiga.',
    flavor: 'Alma atrapada entre mundos, hambrienta.',
    keywords: [], collectorNumber: 53, aiTags: ['evasion', 'discard'], unique: false,
    effects: [{ kind: 'passive', id: 'unblockable-ghost' }, { kind: 'discard', amount: 1 }],
    vfx: { summonEffect: 'ghostly-wail', attackEffect: 'spectral-touch' },
  }),
  defineCard({
    id: 'esqueleto-guerrero', name: 'Esqueleto Guerrero', faction: 'shadow', type: 'unit', subtype: 'Undead',
    rarity: 'common', cost: factionCost('shadow', 1, 1), attack: 2, health: 2, range: 1, movement: 1,
    rules: 'Cuando muere, puede resucitar gastando 2 de Esencia Oscura.',
    flavor: 'Soldado que no conoce el verdadero reposo.',
    keywords: [], collectorNumber: 54, aiTags: ['undead', 'sacrifice'], unique: false,
    effects: [{ kind: 'passive', id: 'undead-resurrection', value: 2 }],
    vfx: { summonEffect: 'bone-rattle', deathEffect: 'bone-scatter' },
  }),
  defineCard({
    id: 'nigromante-oscuro', name: 'Nigromante Oscuro', faction: 'shadow', type: 'unit', subtype: 'Humanoid',
    rarity: 'rare', cost: factionCost('shadow', 2, 2), attack: 3, health: 2, range: 2, movement: 1,
    rules: 'Cuando una unidad aliada muere, roba una carta. Tus hechizos drenan Vida.',
    flavor: 'Maestro que reescribe el destino de los muertos.',
    keywords: [], collectorNumber: 55, aiTags: ['finisher', 'draw'], unique: false,
    effects: [{ kind: 'draw', amount: 1 }, { kind: 'passive', id: 'drain-spells', value: 1 }],
    vfx: { summonEffect: 'death-magic', persistentEffect: 'curse-aura' },
  }),
  defineCard({
    id: 'maldicion-sombra', name: 'Maldición Sombra', faction: 'shadow', type: 'persistent', subtype: 'Encantamiento',
    rarity: 'uncommon', cost: factionCost('shadow', 1, 2),
    rules: 'Una unidad enemiga pierde 1 Vida al final de cada turno.',
    flavor: 'Marca invisible que consume vitalidad.',
    keywords: [], collectorNumber: 56, aiTags: ['control', 'damage'], unique: false,
    effects: [{ kind: 'passive', id: 'curse-drain-health', value: 1 }],
    vfx: { impactEffect: 'curse-mark', persistentEffect: 'drain-aura' },
  }),
  defineCard({
    id: 'vampiro-siniestro', name: 'Vampiro Siniestro', faction: 'shadow', type: 'unit', subtype: 'Humanoid',
    rarity: 'uncommon', cost: factionCost('shadow', 2, 1), attack: 3, health: 2, range: 1, movement: 2,
    rules: 'Cuando ataca, drena daño igual como Vida para ti.',
    flavor: 'Inmortal que se alimenta de desesperación.',
    keywords: [], collectorNumber: 57, aiTags: ['lifedrain', 'aggressive'], unique: false,
    effects: [{ kind: 'passive', id: 'lifesteal-on-attack', value: 1 }],
    vfx: { summonEffect: 'vampire-rise', attackEffect: 'blood-drain' },
  }),
  defineCard({
    id: 'pesadilla-mortal', name: 'Pesadilla Mortal', faction: 'shadow', type: 'unit', subtype: 'Horror',
    rarity: 'rare', cost: factionCost('shadow', 2, 3), attack: 4, health: 3, range: 1, movement: 1,
    rules: 'Cuando entra en juego, descarta 2 cartas enemigas. Esas unidades pierden -1 Vida.',
    flavor: 'Terror que consume cordura y esperanza.',
    keywords: [], collectorNumber: 58, aiTags: ['finisher', 'discard'], unique: false,
    effects: [{ kind: 'discard', amount: 2 }, { kind: 'passive', id: 'discarded-units-weaken', value: 1 }],
    vfx: { summonEffect: 'nightmare-rise', persistentEffect: 'dread-aura' },
  }),
];

const voidCards: readonly CardDefinition[] = [
  defineCard({
    id: 'fuente-vacio', name: 'Fuente Vacío', faction: 'void', type: 'mana', subtype: 'Fuente',
    rarity: 'common', cost: factionCost('void', 0),
    rules: 'Agota esta fuente: genera 1 de Esencia Distorsionada.',
    flavor: 'Energía que rompió los límites del espacio.',
    keywords: [], collectorNumber: 59, aiTags: ['resource'], unique: false, effects: [],
    vfx: { persistentEffect: 'void-source-distortion' }, sfx: { play: 'resource-void' },
  }),
  defineCard({
    id: 'basilisco-caos', name: 'Basilisco del Caos', faction: 'void', type: 'unit', subtype: 'Bestia',
    rarity: 'uncommon', cost: factionCost('void', 2, 1), attack: 2, health: 3, range: 2, movement: 1,
    rules: 'Gaze mortal. Cuando ataca, sujeta a la unidad objetivo por 1 turno.',
    flavor: 'Criatura que distorsiona la realidad a su paso.',
    keywords: [], collectorNumber: 60, aiTags: ['control', 'ranged'], unique: false,
    effects: [{ kind: 'freeze', duration: 1 }],
    vfx: { summonEffect: 'chaos-roar', attackEffect: 'petrifying-gaze' },
  }),
  defineCard({
    id: 'quimera-caos', name: 'Quimera del Caos', faction: 'void', type: 'unit', subtype: 'Horror',
    rarity: 'uncommon', cost: factionCost('void', 2, 2), attack: 3, health: 3, range: 2, movement: 2,
    rules: 'Cuando entra en juego, copia una habilidad de otra unidad aliada.',
    flavor: 'Abominación que es todo y nada a la vez.',
    keywords: [], collectorNumber: 61, aiTags: ['synergy', 'shapeshifter'], unique: false,
    effects: [{ kind: 'passive', id: 'copy-ally-ability' }],
    vfx: { summonEffect: 'chimera-morph', persistentEffect: 'chaos-aura' },
  }),
  defineCard({
    id: 'devorador-entropico', name: 'Devorador Entrópico', faction: 'void', type: 'unit', subtype: 'Horror',
    rarity: 'rare', cost: factionCost('void', 2, 2), attack: 3, health: 4, range: 1, movement: 1, resistance: 2,
    rules: 'Cuando una estructura es destruida, drena su Resistencia como Vida.',
    flavor: 'Entidad que consume orden y estructura.',
    keywords: [], collectorNumber: 62, aiTags: ['durable', 'structure-tech'], unique: false,
    effects: [{ kind: 'passive', id: 'devour-structure-resistance' }],
    vfx: { summonEffect: 'entropy-birth', persistentEffect: 'corruption-aura' },
  }),
  defineCard({
    id: 'leviatan-abismal', name: 'Leviatán Abismal', faction: 'void', type: 'unit', subtype: 'Bestia',
    rarity: 'mythic', cost: factionCost('void', 3, 4), attack: 6, health: 5, range: 1, movement: 1,
    rules: 'Impulso. Cuando ataca, distorsiona el espacio: mueve todas las unidades 1 casilla.',
    flavor: 'Horror primordial del vacío sin fondo.',
    keywords: ['impulse'], collectorNumber: 63, aiTags: ['finisher', 'control'], unique: true,
    effects: [{ kind: 'adjacent-damage', amount: 1, includeAllies: true }],
    vfx: { summonEffect: 'leviathan-awaken', attackEffect: 'void-collapse', deathEffect: 'reality-break' },
  }),
  defineCard({
    id: 'aniquilacion-vacio', name: 'Aniquilación del Vacío', faction: 'void', type: 'instant', subtype: 'Conjuro',
    rarity: 'rare', cost: factionCost('void', 2, 3),
    rules: 'Destruye todas las estructuras enemigas. Gana Esencia igual a su Resistencia.',
    flavor: 'El final de todas las cosas.',
    keywords: [], collectorNumber: 64, aiTags: ['removal', 'board-wipe'], unique: false,
    effects: [{ kind: 'passive', id: 'destroy-all-structures' }],
    vfx: { impactEffect: 'void-annihilation' },
  }),
  defineCard({
    id: 'paradoja-vacio', name: 'Paradoja del Vacío', faction: 'void', type: 'persistent', subtype: 'Portal',
    rarity: 'uncommon', cost: factionCost('void', 1, 3),
    rules: 'Una vez por turno, una unidad aliada puede cambiar de lado de forma temporal.',
    flavor: 'Puerta a realidades que se contradicen.',
    keywords: [], collectorNumber: 65, aiTags: ['movement', 'control'], unique: false,
    effects: [{ kind: 'refresh-move' }],
    vfx: { impactEffect: 'paradox-portal', persistentEffect: 'reality-rift' },
  }),
  defineCard({
    id: 'horror-abisal', name: 'Horror Abisal', faction: 'void', type: 'unit', subtype: 'Horror',
    rarity: 'uncommon', cost: factionCost('void', 1, 2), attack: 2, health: 2, range: 2, movement: 1,
    rules: 'Cuando ataca, todas las unidades enemigas pierden 1 Movimiento este turno.',
    flavor: 'Presencia que congela la voluntad de actuar.',
    keywords: [], collectorNumber: 66, aiTags: ['control', 'ranged'], unique: false,
    effects: [{ kind: 'passive', id: 'slow-enemies-on-attack', value: 1 }],
    vfx: { summonEffect: 'horror-screech', attackEffect: 'dread-beam' },
  }),
];

export const CARDS = Object.freeze([...furyCards, ...arcaneCards, ...natureCards, ...orderCards, ...shadowCards, ...voidCards]) as readonly CardDefinition[];

if (CARDS.length !== 66 || new Set(CARDS.map((card) => card.id)).size !== 66) {
  throw new Error('El conjunto NEX-01 debe contener exactamente 66 cartas con identificadores únicos.');
}

export const CARD_BY_ID: Readonly<Record<string, CardDefinition>> = Object.freeze(
  Object.fromEntries(CARDS.map((card) => [card.id, card])),
);

export const cardsForFaction = (faction: FactionId): readonly CardDefinition[] =>
  CARDS.filter((card) => card.faction === faction);

export const MANDATORY_CARD_IDS = [
  'fuente-furia', 'sabueso-brasa', 'berserker-ignivoro', 'dragon-caldera', 'lluvia-ceniza', 'forja-carmesi',
  'fuente-arcana', 'centinela-cristal', 'tejedora-escarcha', 'prision-glacial', 'cometa-arcano', 'torre-horizonte',
] as const;
