import type { FactionDefinition, FactionId } from './types';

export const FACTIONS = [
  {
    id: 'fury',
    name: 'Furia',
    description: 'Agresión volcánica, criaturas veloces y daño inmediato.',
    color: '#b72d20',
    accentColor: '#ff9a3d',
    icon: 'flame',
    unlocked: true,
    themes: ['fuego', 'agresión', 'sacrificio'],
  },
  {
    id: 'arcane',
    name: 'Arcano',
    description: 'Control del campo, hielo y manipulación del conocimiento.',
    color: '#2356a8',
    accentColor: '#75dcff',
    icon: 'crystal',
    unlocked: true,
    themes: ['hielo', 'control', 'robo'],
  },
  {
    id: 'nature',
    name: 'Naturaleza',
    description: 'Crecimiento, curación y reservas de Esencia abundantes.',
    color: '#39753a',
    accentColor: '#a7db67',
    icon: 'leaf',
    unlocked: true,
    themes: ['curación', 'crecimiento', 'resistencia'],
  },
  {
    id: 'order',
    name: 'Orden',
    description: 'Formaciones defensivas, escudos y grandes estructuras.',
    color: '#d8caa4',
    accentColor: '#f2cf68',
    icon: 'sun-shield',
    unlocked: true,
    themes: ['defensa', 'soldados', 'muros'],
  },
  {
    id: 'shadow',
    name: 'Sombra',
    description: 'Veneno, descarte y poder obtenido del cementerio.',
    color: '#261d2d',
    accentColor: '#8d51aa',
    icon: 'eclipse',
    unlocked: true,
    themes: ['veneno', 'cementerio', 'robo de vida'],
  },
  {
    id: 'void',
    name: 'Vacío',
    description: 'Portales y distorsiones que reescriben el espacio.',
    color: '#59327d',
    accentColor: '#c775ff',
    icon: 'portal',
    unlocked: true,
    themes: ['portales', 'teletransporte', 'distorsión'],
  },
  {
    id: 'duna',
    name: 'Duna',
    description: 'El Tribunal de Arena: paga con tu propia Vida y gana cuando vas perdiendo.',
    color: '#c9a86a',
    accentColor: '#ffd76a',
    icon: 'scales',
    unlocked: true,
    themes: ['ofrenda', 'juicio', 'remontada'],
  },
  {
    id: 'fimbul',
    name: 'Fimbul',
    description: 'El invierno que no termina: desafía a lo más fuerte y pega más cuanto peor está.',
    color: '#5a5f66',
    accentColor: '#d8a944',
    icon: 'axe',
    unlocked: true,
    themes: ['desafío', 'furor', 'invierno'],
  },
  {
    id: 'samsara',
    name: 'Samsara',
    description: 'La rueda que no se detiene: sus unidades mueren y vuelven mayores.',
    color: '#e08a2c',
    accentColor: '#ffd27a',
    icon: 'lotus',
    unlocked: true,
    themes: ['renacer', 'avatar', 'ciclo'],
  },
  {
    id: 'jade',
    name: 'Jade',
    description: 'El Mandato del Cielo: un solo favor que cambia de bando y decide quién gobierna la mesa.',
    color: '#b8322c',
    accentColor: '#f2c14e',
    icon: 'seal',
    unlocked: true,
    themes: ['mandato', 'elementos', 'corte'],
  },
  {
    id: 'olimpo',
    name: 'Olimpo',
    description: 'La medida y el exceso: cada golpe al Nexo enemigo te hace más grande y más frágil a la vez.',
    color: '#e8e2d4',
    accentColor: '#cf9b3f',
    icon: 'laurel',
    unlocked: true,
    themes: ['hybris', 'metamorfosis', 'desmesura'],
  },
  {
    id: 'sol',
    name: 'Quinto Sol',
    description: 'El que hay que alimentar: sacrifica a tus propias unidades y cuenta los días que faltan.',
    color: '#c98b4b',
    accentColor: '#f5c33b',
    icon: 'sun-disc',
    unlocked: true,
    themes: ['sacrificio', 'cuenta del sol', 'ofrenda'],
  },
  {
    id: 'bestiario',
    name: 'Bestiario',
    description: 'Las bestias que ningún pueblo pudo domesticar: el cuerpo más grande y directo de la mesa.',
    color: '#1c2e22',
    accentColor: '#c9932e',
    icon: 'claw',
    unlocked: true,
    themes: ['bestias', 'tamaño', 'palabras clave'],
  },
] as const satisfies readonly FactionDefinition[];

export const FACTION_BY_ID = Object.freeze({
  fury: FACTIONS[0],
  arcane: FACTIONS[1],
  nature: FACTIONS[2],
  order: FACTIONS[3],
  shadow: FACTIONS[4],
  void: FACTIONS[5],
  duna: FACTIONS[6],
  fimbul: FACTIONS[7],
  samsara: FACTIONS[8],
  jade: FACTIONS[9],
  olimpo: FACTIONS[10],
  sol: FACTIONS[11],
  bestiario: FACTIONS[12],
}) satisfies Readonly<Record<FactionId, FactionDefinition>>;

export const PLAYABLE_FACTIONS = FACTIONS.filter((faction) => faction.unlocked);
